export const list = [
    {
        title: '火车',
        originaltitle: '火車',
        author: '宫部美雪',
        date: '2016-01',
        rate: 7.7,
        img: 's28341617.jpg',
        tags: ['推理', '社会派'],
        status: 'done'
    },
    {
        title: '模仿犯',
        originaltitle: '',
        author: '宫部美雪',
        date: '2013-03',
        rate: 8.3,
        img: 's26712402.jpg',
        tags: ['推理', '社会派'],
        status: 'buy'
    },
    {
        title: '理由',
        originaltitle: '',
        author: '宫部美雪',
        date: '2015-02',
        rate: 8.0,
        img: 's27995096.jpg',
        tags: ['推理', '社会派'],
        status: 'buy'
    },
    {
        title: '希望庄',
        originaltitle: '希望荘',
        author: '宫部美雪',
        date: '2023-11',
        rate: 7.2,
        img: 's34694275.jpg',
        tags: ['推理'],
        status: 'new'
    },
    {
        title: '嫌疑人X的献身',
        originaltitle: '容疑者Xの献身',
        author: '东野圭吾',
        date: '2008-09',
        rate: 8.9,
        img: 's3254244.jpg',
        tags: ['推理'],
        status: 'done'
    },
    {
        title: '白夜行',
        originaltitle: '白夜行',
        author: '东野圭吾',
        date: '2013-01',
        rate: 9.2,
        img: 's24514468.jpg',
        tags: ['推理'],
        status: 'done'
    },
    {
        title: '恶意',
        originaltitle: '悪意',
        author: '东野圭吾',
        date: '2016-11',
        rate: 8.7,
        img: 's29827014.jpg',
        tags: ['推理'],
        status: 'buy'
    },
    {
        title: '解忧杂货铺',
        originaltitle: 'ナミヤ雑貨店の奇蹟',
        author: '东野圭吾',
        date: '2014-05',
        rate: 8.5,
        img: 's27264181.jpg',
        tags: ['推理'],
        status: 'buy'
    },
    {
        title: '沉睡的人鱼之家',
        originaltitle: '人魚の眠る家',
        author: '东野圭吾',
        date: '2023-10',
        rate: 7.6,
        img: 's34694222.jpg',
        tags: ['推理'],
        status: 'buy'
    },
    {
        title: '从前我死去的家',
        originaltitle: 'むかし僕が死んだ家',
        author: '东野圭吾',
        date: '2018-08',
        rate: 7.8,
        img: 's30014642.jpg',
        tags: ['推理'],
        status: 'buy'
    },
    {
        title: '秘密',
        originaltitle: '',
        author: '东野圭吾',
        date: '2017-11',
        rate: 8.0,
        img: 's30014644.jpg',
        tags: ['推理'],
        status: 'buy'
    },
    {
        title: '十角馆事件',
        originaltitle: '十角館の殺人',
        author: '绫辻行人',
        date: '2016-06',
        rate: 7.0,
        img: 's28775789.jpg',
        no: 1,
        tags: ['推理', '馆系列'],
        status: 'new'
    },
    {
        title: '水车馆事件',
        originaltitle: '水車館の殺人',
        author: '绫辻行人',
        date: '2016-06',
        rate: 6.7,
        img: 's28775780.jpg',
        no: 2,
        tags: ['推理', '馆系列'],
        status: 'new'
    },
    {
        title: '迷宫馆事件',
        originaltitle: '迷路館の殺人',
        author: '绫辻行人',
        date: '2016-06',
        rate: 7.7,
        img: 's28775768.jpg',
        no: 3,
        tags: ['推理', '馆系列'],
        status: 'buy'
    },
    {
        title: '人偶馆事件',
        originaltitle: '人形館の殺人',
        author: '绫辻行人',
        date: '2016-06',
        rate: 5.8,
        img: 's28775781.jpg',
        no: 4,
        tags: ['推理', '馆系列'],
        status: 'new'
    },
    {
        title: '钟表馆事件',
        originaltitle: '時計館の殺人',
        author: '绫辻行人',
        date: '2016-06',
        rate: 8.3,
        img: 's28775794.jpg',
        no: 5,
        tags: ['推理', '馆系列'],
        status: 'buy'
    },
    {
        title: '黑猫馆事件',
        originaltitle: '黒猫館の殺人',
        author: '绫辻行人',
        date: '2016-06',
        rate: 7.3,
        img: 's28775772.jpg',
        no: 6,
        tags: ['推理', '馆系列'],
        status: 'new'
    },
    {
        title: '暗黑馆事件',
        originaltitle: '暗黒館の殺人',
        author: '绫辻行人',
        date: '2016-06',
        rate: 7.5,
        img: 's28775786.jpg',
        no: 7,
        tags: ['推理', '馆系列'],
        status: 'new'
    },
    {
        title: '惊吓馆事件',
        originaltitle: 'びっくり館の殺人',
        author: '绫辻行人',
        date: '2016-06',
        rate: 5.2,
        img: 's28775792.jpg',
        no: 8,
        tags: ['推理', '馆系列'],
        status: 'new'
    },
    {
        title: '奇面馆事件',
        originaltitle: '奇面館の殺人',
        author: '绫辻行人',
        date: '2016-06',
        rate: 6.6,
        img: 's28775777.jpg',
        no: 9,
        tags: ['推理', '馆系列'],
        status: 'new'
    },
    {
        title: '占星术杀人魔法',
        originaltitle: '占星術の殺人',
        author: '岛田庄司',
        date: '2019-07',
        rate: 8.3,
        img: 's33436541.jpg',
        tags: ['推理'],
        status: 'buy'
    },
    {
        title: '19年间谋杀小叙',
        originaltitle: '',
        author: '那多',
        date: '2018-07',
        rate: 8.1,
        img: 's30008412.jpg',
        tags: ['推理'],
        status: 'done'
    },
    {
        title: '绝叫',
        originaltitle: '絕叫',
        author: '叶真中显',
        date: '2020-07',
        rate: 8.9,
        img: 's33685372.jpg',
        tags: ['推理', '社会派'],
        status: 'done'
    },
    {
        title: '恶女的告白',
        originaltitle: 'ロング・アフタヌーン',
        author: '叶真中显',
        date: '2024-09',
        rate: 8.3,
        img: 's34917944.jpg',
        tags: ['推理'],
        status: 'buy'
    },
    {
        title: '邻居',
        originaltitle: '火の粉',
        author: '雫井修介',
        date: '2023-06',
        rate: 7.5,
        img: 's34528340.jpg',
        tags: ['推理', '社会派'],
        status: 'done'
    },
    {
        title: '希望之罪',
        originaltitle: '',
        author: '雫井脩介',
        date: '2021-06',
        rate: 7.8,
        img: 's33886147.jpg',
        tags: ['推理'],
        status: 'buy'
    },
    {
        title: '检察方的罪人',
        originaltitle: '検察侧の罪人',
        author: '雫井脩介',
        date: '2019-07',
        rate: 7.7,
        img: 's32375944.jpg',
        tags: ['推理'],
        status: 'new'
    },
    {
        title: '六个说谎的大学生',
        originaltitle: '六人の嘘つきな大学生',
        author: '浅仓秋成',
        date: '2023-04',
        rate: 7.7,
        img: 's34497205.jpg',
        tags: ['推理'],
        status: 'buy'
    },
    {
        title: '凶人馆谜案',
        originaltitle: '兇人邸の殺人',
        author: '今村昌弘',
        date: '2022-09',
        rate: 7.5,
        img: 's34298754.jpg',
        tags: ['推理'],
        status: 'buy'
    },
    {
        title: '尸人庄谜案',
        originaltitle: '屍人荘の殺人',
        author: '今村昌弘',
        date: '2019-09',
        rate: 6.9,
        img: 's33296332.jpg',
        tags: ['推理'],
        status: 'new'
    },
    {
        title: '心灵侦探城塚翡翠',
        originaltitle: 'medium 霊媒探偵城塚翡翠',
        author: '相泽沙呼',
        date: '2021-04',
        rate: 7.7,
        img: 's33919727.jpg',
        tags: ['推理'],
        status: 'new'
    },
    {
        title: '城塚翡翠倒叙集',
        originaltitle: 'invert 城塚翡翠倒叙集',
        author: '相泽沙呼',
        date: '2022-09',
        rate: 6.2,
        img: 's34313221.jpg',
        tags: ['推理'],
        status: 'new'
    },
    {
        title: '时空旅行者的沙漏',
        originaltitle: '時空旅行者の砂時計',
        author: '方丈贵惠',
        date: '2021-05',
        rate: 7.5,
        img: 's33880048.jpg',
        no: 1,
        tags: ['推理'],
        status: 'buy'
    },
    {
        title: '孤岛的来访者',
        originaltitle: '孤島の来訪者',
        author: '方丈贵惠',
        date: '2023-04',
        rate: 7.7,
        img: 's34489948.jpg',
        no: 2,
        tags: ['推理'],
        status: 'buy'
    },
    {
        title: '献给名侦探的甜美死亡',
        originaltitle: '名探偵に甘美なる死を',
        author: '方丈贵惠',
        date: '2023-08',
        rate: 7.9,
        img: 's34606347.jpg',
        no: 3,
        tags: ['推理'],
        status: 'buy'
    },
    {
        title: '名侦探的献祭',
        originaltitle: '名探偵のいけにえ',
        author: '白井智之',
        date: '2023-09',
        rate: 7.1,
        img: 's34681654.jpg',
        tags: ['推理'],
        status: 'buy'
    },
    {
        title: '死神广播',
        originaltitle: '死体の汁を啜れ',
        author: '白井智之',
        date: '2024-08',
        rate: 8.0,
        img: 's34924609.jpg',
        tags: ['推理'],
        status: 'buy'
    },
    {
        title: '无人逝去',
        originaltitle: 'そして誰も死ななかった',
        author: '白井智之',
        date: '2023-07',
        rate: 6.8,
        img: 's34565616.jpg',
        tags: ['推理'],
        status: 'buy'
    },
    {
        title: '魍魉之匣（上）',
        originaltitle: '魍魎の匣',
        author: '京极夏彦',
        date: '2009-01',
        rate: 8.4,
        img: 's3381235.jpg',
        tags: ['推理'],
        status: 'buy'
    },
    {
        title: '魍魉之匣（下）',
        originaltitle: '魍魎の匣',
        author: '京极夏彦',
        date: '2009-01',
        rate: 8.6,
        img: 's3381238.jpg',
        tags: ['推理'],
        status: 'buy'
    },
    {
        title: '独眼少女',
        originaltitle: '隻眼の少女',
        author: '麻耶雄嵩',
        date: '2024-09',
        rate: 7.7,
        img: 's34949800.jpg',
        tags: ['推理'],
        status: 'buy'
    },
    {
        title: '蓝玫瑰不会安眠',
        originaltitle: 'ブルーローズは眠らない',
        author: '市川忧人',
        date: '2019-12',
        rate: 7.0,
        img: 's33529005.jpg',
        tags: ['推理'],
        status: 'buy'
    },
    {
        title: '水母不会冻结',
        originaltitle: 'ジェリーフィッシュは凍らない',
        author: '市川忧人',
        date: '2019-12',
        rate: 6.8,
        img: 's33529003.jpg',
        tags: ['推理'],
        status: 'buy'
    },
    {
        title: '玻璃鸟不会归来',
        originaltitle: 'グラスバードは還らない',
        author: '市川忧人',
        date: '2020-01',
        rate: 6.2,
        img: 's33529007.jpg',
        tags: ['推理'],
        status: 'buy'
    },
    {
        title: '埋骨场不会言说',
        originaltitle: 'ボーンヤードは語らない',
        author: '市川忧人',
        date: '2022-05',
        rate: 6.5,
        img: 's34222511.jpg',
        tags: ['推理'],
        status: 'buy'
    },
    {
        title: '黑牢城',
        originaltitle: '黒牢城',
        author: '米泽穗信',
        date: '2023-06',
        rate: 7.8,
        img: 's34555485.jpg',
        tags: ['推理'],
        status: 'buy'
    },
    {
        title: '诗人',
        originaltitle: 'The Poet',
        author: '迈克尔•康奈利',
        date: '2018-11',
        rate: 8.4,
        img: 's29904068.jpg',
        no: 1,
        tags: ['推理'],
        status: 'buy'
    },
    {
        title: '混凝土里的金发女郎',
        originaltitle: 'The Concrete Blonde',
        author: '迈克尔•康奈利',
        date: '2019-06',
        rate: 8.3,
        img: 's32312733.jpg',
        no: 2,
        tags: ['推理'],
        status: 'buy'
    },
    {
        title: '如厌魅附体之物',
        originaltitle: '厭魅の如き憑くもの',
        author: '三津田信三',
        date: '2024-09',
        rate: 7.6,
        img: 's35005214.jpg',
        no: 1,
        tags: ['推理', '刀城言耶系列'],
        status: 'buy'
    },
    {
        title: '如凶鸟忌讳之物',
        originaltitle: '凶鳥の如き忌むもの',
        author: '三津田信三',
        date: '2023-04',
        rate: 7.0,
        img: 's34597940.jpg',
        no: 2,
        tags: ['推理', '刀城言耶系列'],
        status: 'new'
    },
    {
        title: '如首无作祟之物',
        originaltitle: '首無の如き祟るもの',
        author: '三津田信三',
        date: '2021-08',
        rate: 8.3,
        img: 's33947872.jpg',
        no: 3,
        tags: ['推理', '刀城言耶系列'],
        status: 'done'
    },
    {
        title: '如山魔嗤笑之物',
        originaltitle: '山魔の如き嗤うもの',
        author: '三津田信三',
        date: '2024-09',
        rate: 8.4,
        img: 's35005241.jpg',
        no: 4,
        tags: ['推理', '刀城言耶系列'],
        status: 'buy'
    },
    {
        title: '如密室自闭之物',
        originaltitle: '密室の如き籠るもの',
        author: '三津田信三',
        date: '2023-04',
        rate: 6.5,
        img: 's34597942.jpg',
        no: 5,
        tags: ['推理', '刀城言耶系列'],
        status: 'new'
    },
    {
        title: '如水魑沉没之物',
        originaltitle: '水魑の如き沈むもの',
        author: '三津田信三',
        date: '2021-08',
        rate: 6.9,
        img: 's33951236.jpg',
        no: 6,
        tags: ['推理', '刀城言耶系列'],
        status: 'buy'
    },
    {
        title: '如生灵双身之物',
        originaltitle: '生霊の如き重るもの',
        author: '三津田信三',
        date: '2024-08',
        rate: 6.9,
        img: 's34737926.jpg',
        no: 7,
        tags: ['推理', '刀城言耶系列'],
        status: 'new'
    },
    {
        title: '如幽女怨怼之物',
        originaltitle: '幽女の如き怨むもの',
        author: '三津田信三',
        date: '2020-12',
        rate: 8.1,
        img: 's33825709.jpg',
        no: 8,
        tags: ['推理', '刀城言耶系列'],
        status: 'buy'
    },
    {
        title: '如碆灵供祭之物',
        originaltitle: '碆霊の如き祀るもの',
        author: '三津田信三',
        date: '2020-12',
        rate: 7.1,
        img: 's33825707.jpg',
        no: 9,
        tags: ['推理', '刀城言耶系列'],
        status: 'new'
    },
    {
        title: '如魔偶招致之物',
        originaltitle: '魔偶の如き齎すもの',
        author: '三津田信三',
        date: '2024-06',
        rate: 6.9,
        img: 's34727235.jpg',
        no: 10,
        tags: ['推理', '刀城言耶系列'],
        status: 'new'
    },
    {
        title: '砂之器',
        originaltitle: '',
        author: '松本清张',
        date: '2019-08',
        rate: 8.0,
        img: 's33439512.jpg',
        tags: ['推理'],
        status: 'buy'
    },
    {
        title: '点与线',
        originaltitle: '',
        author: '松本清张',
        date: '2019-11',
        rate: 8.1,
        img: 's33576172.jpg',
        tags: ['推理'],
        status: 'buy'
    },
    {
        title: '零的焦点',
        originaltitle: '',
        author: '松本清张',
        date: '2019-09',
        rate: 8.0,
        img: 's33487564.jpg',
        tags: ['推理'],
        status: 'buy'
    },
    {
        title: '阴兽',
        originaltitle: '',
        author: '江户川乱步',
        date: '2016-08',
        rate: 8.8,
        img: 's28914519.jpg',
        tags: ['推理'],
        status: 'buy'
    },
    {
        title: '人间椅子',
        originaltitle: '',
        author: '江户川乱步',
        date: '2016-08',
        rate: 8.7,
        img: 's28982536.jpg',
        tags: ['推理'],
        status: 'buy'
    },
    {
        title: '孤岛之鬼',
        originaltitle: '',
        author: '江户川乱步',
        date: '2016-08',
        rate: 8.6,
        img: 's29108993.jpg',
        tags: ['推理'],
        status: 'new'
    },
    {
        title: 'D坂殺人事件',
        originaltitle: '',
        author: '江户川乱步',
        date: '2016-08',
        rate: 7.8,
        img: 's29245186.jpg',
        tags: ['推理'],
        status: 'new'
    },
    {
        title: '两分铜币',
        originaltitle: '',
        author: '江户川乱步',
        date: '2016-08',
        rate: 7.8,
        img: 's29360333.jpg',
        tags: ['推理'],
        status: 'buy'
    },
    {
        title: '帕诺拉马岛奇谭',
        originaltitle: '',
        author: '江户川乱步',
        date: '2016-08',
        rate: 7.9,
        img: 's29443384.jpg',
        tags: ['推理'],
        status: 'new'
    },
    {
        title: '白兔',
        originaltitle: 'ホワイトラビット',
        author: '伊坂幸太郎',
        date: '2021-11',
        rate: 7.6,
        img: 's34020517.jpg',
        tags: ['推理'],
        status: 'buy'
    },
    {
        title: '解体诸因',
        originaltitle: '',
        author: '西泽保彦',
        date: '2017-08',
        rate: 7.5,
        img: 's29502450.jpg',
        no: 1,
        tags: ['推理', '匠千晓系列'],
        status: 'buy'
    },
    {
        title: '怪屋谜案',
        originaltitle: '変な家',
        author: '雨穴',
        date: '2023-07',
        rate: 6.7,
        img: 's34530490.jpg',
        tags: ['推理'],
        status: 'done'
    },
    {
        title: '怪画谜案',
        originaltitle: '変な絵',
        author: '雨穴',
        date: '2024-07',
        rate: 7.5,
        img: 's34903230.jpg',
        tags: ['推理'],
        status: 'done'
    },
    {
        title: '桶川跟踪狂杀人事件',
        originaltitle: '桶川ストーカー殺人事件',
        author: '清水洁',
        date: '2021-02',
        rate: 9.0,
        img: 's34072986.jpg',
        tags: ['推理'],
        status: 'done'
    },
    {
        title: '歌唱的白骨',
        originaltitle: '',
        author: '奥斯汀•弗里曼',
        date: '2010-09',
        rate: 7.6,
        img: 's4450006.jpg',
        tags: ['推理'],
        status: 'buy'
    },
    {
        title: '三口棺材',
        originaltitle: 'The Three Coffins',
        author: '约翰•迪克森•卡尔',
        date: '2019-03',
        rate: 7.7,
        img: 's32264143.jpg',
        tags: ['推理'],
        status: 'buy'
    },
    {
        title: '犹大之窗',
        originaltitle: 'The Judas Window',
        author: '约翰•迪克森•卡尔',
        date: '2019-06',
        rate: 8.2,
        img: 's32313716.jpg',
        tags: ['推理'],
        status: 'buy'
    },
    {
        title: '扭曲的铰链',
        originaltitle: 'The Crooked Hinge',
        author: '约翰•迪克森•卡尔',
        date: '2019-09',
        rate: 6.5,
        img: 's33465078.jpg',
        tags: ['推理'],
        status: 'buy'
    },

    {
        title: '怪兽保护协会',
        originaltitle: '',
        author: '约翰·斯卡尔齐',
        date: '2023-10',
        rate: 7.0,
        img: 's34663283.jpg',
        tags: ['科幻'],
        status: 'buy'
    },
    {
        title: '麦田里的守望者',
        originaltitle: 'The Catcher in the Rye',
        author: 'J. D. 塞林格',
        date: '2020-07',
        rate: 8.6,
        img: 's33764854.jpg',
        tags: ['小说'],
        status: 'buy'
    },
    {
        title: '杀死一只知更鸟',
        originaltitle: 'To Kill A Mockingbird',
        author: '哈珀·李',
        date: '2017-02',
        rate: 9.3,
        img: 's29214279.jpg',
        tags: ['成长小说'],
        status: 'done'
    },
    {
        title: '烛烬',
        originaltitle: 'A gyertyák csonkig égnek',
        author: '马洛伊·山多尔',
        date: '2015-11',
        rate: 8.6,
        img: 's28290984.jpg',
        tags: ['小说'],
        status: 'buy'
    },
    {
        title: '1367',
        originaltitle: '',
        author: '陈浩基',
        date: '2014-06',
        rate: 9.1,
        img: 's33699260.jpg',
        tags: ['推理'],
        status: 'buy'
    },
    {
        title: '玫瑰的名字',
        originaltitle: 'Il Nome Della Rosa',
        author: '翁贝托•埃科',
        date: '2020-05',
        rate: 8.6,
        img: 's33631404.jpg',
        tags: ['推理'],
        status: 'buy'
    },
    {
        title: '华氏451',
        originaltitle: 'Fahrenheit 451',
        author: '雷•布拉德伯里',
        date: '2017-017',
        rate: 8.3,
        img: 's29526119.jpg',
        tags: ['科幻'],
        status: 'buy'
    },
    {
        title: '小王子',
        originaltitle: '',
        author: '安托万•德•圣埃克苏佩里',
        date: '2013-01',
        rate: 8.1,
        img: 's28317563.jpg',
        tags: ['小说'],
        status: 'done'
    },
    {
        title: '房思琪的初恋乐园',
        originaltitle: '',
        author: '林奕含',
        date: '2018-02',
        rate: 9.2,
        img: 's29451142.jpg',
        tags: ['小说', 'Top250'],
        status: 'buy'
    },
    {
        title: '夜晚的潜水艇',
        originaltitle: '',
        author: '陈春成',
        date: '2020-09',
        rate: 8.3,
        img: 's33718940.jpg',
        tags: ['小说'],
        status: 'buy'
    },
    {
        title: '过于喧嚣的孤独',
        originaltitle: 'Příliš hlučna samota',
        author: '博胡米尔·赫拉巴尔',
        date: '2017-10',
        rate: 8.7,
        img: 's29596761.jpg',
        tags: ['小说'],
        status: 'buy'
    },
    {
        title: '太古和其他的时间',
        originaltitle: 'Prawiek i inne czasy',
        author: '奥尔加·托卡尔丘克',
        date: '2017-12',
        rate: 8.9,
        img: 's34530684.jpg',
        tags: ['小说'],
        status: 'buy'
    },
    {
        title: '白天的房子，夜晚的房子',
        originaltitle: 'Dom dzienny, dom nocny',
        author: '奥尔加·托卡尔丘克',
        date: '2017-12',
        rate: 8.6,
        img: 's34530686.jpg',
        tags: ['小说'],
        status: 'buy'
    },
    {
        title: '地球副本',
        originaltitle: 'Faller',
        author: '威尔·麦金托什',
        date: '2019-07',
        rate: 6.1,
        img: 's33324949.jpg',
        tags: ['科幻'],
        status: 'buy'
    },
    {
        title: '彩虹尽头',
        originaltitle: 'Rainbows End',
        author: '弗诺·文奇',
        date: '2019-07',
        rate: 7.0,
        img: 's33316329.jpg',
        tags: ['科幻'],
        status: 'buy'
    },
    {
        title: '真名实姓',
        originaltitle: 'TRUE NAMES AND THE OPENING OF THE CYBERSPACE FRONTIER',
        author: '弗诺·文奇',
        date: '2019-06',
        rate: 8.2,
        img: 's32330953.jpg',
        tags: ['科幻'],
        status: 'done'
    },
    {
        title: '你一生的故事',
        originaltitle: 'STORIES OF YOUR LIFE AND OTHERS',
        author: '特德·姜',
        date: '2019-12',
        rate: 8.7,
        img: 's33516836.jpg',
        tags: ['科幻'],
        status: 'buy'
    },
    {
        title: '呼吸',
        originaltitle: 'Exhalation: Stories',
        author: '特德·姜',
        date: '2019-12',
        rate: 8.6,
        img: 's33519539.jpg',
        tags: ['科幻'],
        status: 'buy'
    },
    {
        title: '百年孤独',
        originaltitle: 'Cien años de soledad',
        author: '加西亚·马尔克斯',
        date: '2017-08',
        rate: 9.5,
        img: 's33542403.jpg',
        tags: ['小说'],
        status: 'buy'
    },
    {
        title: '霍乱时期的爱情',
        originaltitle: 'El Amor En Los Tiempos Del Colera',
        author: '加西亚·马尔克斯',
        date: '2015-06',
        rate: 8.9,
        img: 's28120604.jpg',
        tags: ['小说'],
        status: 'done'
    },
    {
        title: '没有人给他写信的上校',
        originaltitle: 'El coronel no tiene quien le escriba',
        author: '加西亚·马尔克斯',
        date: '2018-06',
        rate: 8.6,
        img: 's29787630.jpg',
        tags: ['小说'],
        status: 'buy'
    },
    {
        title: '一桩事先张扬的凶杀案',
        originaltitle: 'Crónica de una muerte anunciada',
        author: '加西亚·马尔克斯',
        date: '2018-08',
        rate: 8.8,
        img: 's29868151.jpg',
        tags: ['小说'],
        status: 'buy'
    },
    {
        title: '倾城之恋',
        originaltitle: '',
        author: '张爱玲',
        date: '2019-03',
        rate: 9.2,
        img: 's30007166.jpg',
        no: 1,
        tags: ['小说', '张爱玲全集'],
        status: 'buy'
    },
    {
        title: '红玫瑰与白玫瑰',
        originaltitle: '',
        author: '张爱玲',
        date: '2019-03',
        rate: 8.9,
        img: 's30007263.jpg',
        no: 2,
        tags: ['小说', '张爱玲全集'],
        status: 'buy'
    },
    {
        title: '半生缘',
        originaltitle: '',
        author: '张爱玲',
        date: '2019-03',
        rate: 9.2,
        img: 's30007351.jpg',
        no: 3,
        tags: ['小说', '张爱玲全集'],
        status: 'new'
    },
    {
        title: '小团圆',
        originaltitle: '',
        author: '张爱玲',
        date: '2019-03',
        rate: 8.5,
        img: 's30007391.jpg',
        no: 4,
        tags: ['小说', '张爱玲全集'],
        status: 'buy'
    },
    {
        title: '怨女',
        originaltitle: '',
        author: '张爱玲',
        date: '2019-03',
        rate: 8.5,
        img: 's30007321.jpg',
        no: 5,
        tags: ['小说', '张爱玲全集'],
        status: 'new'
    },
    {
        title: '流言',
        originaltitle: '',
        author: '张爱玲',
        date: '2019-06',
        rate: 9.0,
        img: 's33296513.jpg',
        no: 6,
        tags: ['小说', '张爱玲全集'],
        status: 'buy'
    },
    {
        title: '华丽缘',
        originaltitle: '',
        author: '张爱玲',
        date: '2019-06',
        rate: 8.1,
        img: 's33318162.jpg',
        no: 7,
        tags: ['小说', '张爱玲全集'],
        status: 'new'
    },
    {
        title: '重访边城',
        originaltitle: '',
        author: '张爱玲',
        date: '2019-07',
        rate: 8.2,
        img: 's33305933.jpg',
        no: 8,
        tags: ['小说', '张爱玲全集'],
        status: 'new'
    },
    {
        title: '红楼梦魇',
        originaltitle: '',
        author: '张爱玲',
        date: '2019-08',
        rate: 8.3,
        img: 's33462471.jpg',
        no: 9,
        tags: ['小说', '张爱玲全集'],
        status: 'buy'
    },
    {
        title: '海上花开',
        originaltitle: '',
        author: '张爱玲',
        date: '2019-08',
        rate: 8.8,
        img: 's34508749.jpg',
        no: 10,
        tags: ['小说', '张爱玲全集'],
        status: 'buy'
    },
    {
        title: '海上花落',
        originaltitle: '',
        author: '张爱玲',
        date: '2021-03',
        rate: 9.0,
        img: 's33462474.jpg',
        no: 11,
        tags: ['小说', '张爱玲全集'],
        status: 'buy'
    },
    {
        title: '六月新娘',
        originaltitle: '',
        author: '张爱玲',
        date: '2020-11',
        rate: 7.8,
        img: 's33751271.jpg',
        no: 12,
        tags: ['小说', '张爱玲全集'],
        status: 'new'
    },
    {
        title: '一曲难忘',
        originaltitle: '',
        author: '张爱玲',
        date: '2023-01',
        rate: 7.2,
        img: 's34416867.jpg',
        no: 13,
        tags: ['小说', '张爱玲全集'],
        status: 'new'
    },
    {
        title: '老人与海',
        originaltitle: '',
        author: '张爱玲',
        date: '2020-08',
        rate: 8.7,
        img: 's33694953.jpg',
        no: 14,
        tags: ['小说', '张爱玲全集'],
        status: 'new'
    },
    {
        title: '克苏鲁神话',
        originaltitle: 'Cthulhu Mythos',
        author: 'H.P.洛夫克拉夫特',
        date: '2016-11',
        rate: 7.5,
        img: 's29103582.jpg',
        no: 1,
        tags: ['小说'],
        status: 'buy'
    },
    {
        title: '克苏鲁神话Ⅱ',
        originaltitle: 'Cthulhu Mythos',
        author: 'H.P.洛夫克拉夫特',
        date: '2018-01',
        rate: 8.2,
        img: 's29625884.jpg',
        no: 2,
        tags: ['小说'],
        status: 'buy'
    },
    {
        title: '克苏鲁神话Ⅲ',
        originaltitle: 'Cthulhu Mythos',
        author: 'H.P.洛夫克拉夫特',
        date: '2019-01',
        rate: 8.0,
        img: 's29951673.jpg',
        no: 3,
        tags: ['小说'],
        status: 'buy'
    },
    {
        title: '克苏鲁神话Ⅳ',
        originaltitle: 'Cthulhu Mythos',
        author: 'H.P.洛夫克拉夫特',
        date: '2021-09',
        rate: 8.0,
        img: 's33956400.jpg',
        no: 4,
        tags: ['小说'],
        status: 'buy'
    },
    {
        title: '克苏鲁神话Ⅴ',
        originaltitle: 'Cthulhu Mythos',
        author: 'H.P.洛夫克拉夫特',
        date: '2024-02',
        rate: 7.7,
        img: 's34781510.jpg',
        no: 5,
        tags: ['小说'],
        status: 'buy'
    },
    {
        title: 'X的悲剧',
        originaltitle: 'The Tragedy of X',
        author: '埃勒里·奎因',
        date: '2017-01',
        rate: 8.2,
        img: 's29244902.jpg',
        no: 1,
        tags: ['小说'],
        status: 'buy'
    },
    {
        title: 'Y的悲剧',
        originaltitle: 'The Tragedy of Y',
        author: '埃勒里·奎因',
        date: '2017-01',
        rate: 8.4,
        img: 's29244915.jpg',
        no: 2,
        tags: ['小说'],
        status: 'buy'
    },
    {
        title: 'Z的悲剧',
        originaltitle: 'The Tragedy of Z',
        author: '埃勒里·奎因',
        date: '2017-01',
        rate: 7.1,
        img: 's29244917.jpg',
        no: 3,
        tags: ['小说'],
        status: 'buy'
    },
    {
        title: '哲瑞·雷恩的最后一案',
        originaltitle: 'Drury Lane’s Last Case',
        author: '埃勒里·奎因',
        date: '2017-01',
        rate: 8.2,
        img: 's29244918.jpg',
        no: 4,
        tags: ['小说'],
        status: 'buy'
    },
    {
        title: '喜鹊谋杀案',
        originaltitle: 'Magpie Murders',
        author: '安东尼•霍洛维茨',
        date: '2019-06',
        rate: 7.4,
        img: 's32325975.jpg',
        tags: ['小说'],
        status: 'buy'
    },
    {
        title: '关键词是谋杀',
        originaltitle: 'The Word is Murder',
        author: '安东尼•霍洛维茨',
        date: '2021-04',
        rate: 7.4,
        img: 's33870684.jpg',
        tags: ['小说'],
        status: 'buy'
    },
    {
        title: '关键句是死亡',
        originaltitle: 'The Sentence is Death',
        author: '安东尼•霍洛维茨',
        date: '2021-07',
        rate: 7.5,
        img: 's33926868.jpg',
        tags: ['小说'],
        status: 'buy'
    },
    {
        title: '猫头鹰谋杀案',
        originaltitle: 'Moonflower Murders',
        author: '安东尼•霍洛维茨',
        date: '2021-09',
        rate: 7.8,
        img: 's33952621.jpg',
        tags: ['小说'],
        status: 'new'
    },
    {
        title: '一把扭曲的匕首',
        originaltitle: 'The Twist of a Knife',
        author: '安东尼•霍洛维茨',
        date: '2024-07',
        rate: 7.4,
        img: 's34899529.jpg',
        tags: ['小说'],
        status: 'new'
    },
    {
        title: '一行杀人的台词',
        originaltitle: 'A Line to Kill',
        author: '安东尼•霍洛维茨',
        date: '2023-05',
        rate: 7.0,
        img: 's34506188.jpg',
        tags: ['犯罪'],
        status: 'new'
    },
    {
        title: '斯泰尔斯庄园奇案',
        originaltitle: 'The Mysterious Affair at Styles',
        author: '阿加莎·克里斯蒂',
        date: '2013-03',
        rate: 7.7,
        img: 's25814170.jpg',
        no: 1,
        tags: ['小说', '阿加莎'],
        status: 'buy'
    },
    {
        title: '罗杰疑案',
        originaltitle: 'The Murder of Roger Ackroyd',
        author: '阿加莎·克里斯蒂',
        date: '2013-03',
        rate: 9.3,
        img: 's25814002.jpg',
        no: 2,
        tags: ['小说', '阿加莎', 'Top250'],
        status: 'done'
    },
    {
        title: '寓所谜案',
        originaltitle: 'The Murder at the Vicarage',
        author: '阿加莎·克里斯蒂',
        date: '2013-03',
        rate: 7.3,
        img: 's25814055.jpg',
        no: 3,
        tags: ['小说', '阿加莎'],
        status: 'new'
    },
    {
        title: '东方快车谋杀案',
        originaltitle: 'Murder on the Orient Express',
        author: '阿加莎·克里斯蒂',
        date: '2013-04',
        rate: 9.0,
        img: 's26344659.jpg',
        no: 4,
        tags: ['小说', '阿加莎'],
        status: 'buy'
    },
    {
        title: '',
        originaltitle: '',
        author: '阿加莎·克里斯蒂',
        date: '2013-04',
        rate: 9.0,
        img: '.jpg',
        no: 5,
        tags: ['小说', '阿加莎'],
        status: 'new'
    },
    {
        title: '悬崖山庄奇案',
        originaltitle: 'Peril At End House',
        author: '阿加莎·克里斯蒂',
        date: '2013-05',
        rate: 8.3,
        img: 's26538460.jpg',
        no: 6,
        tags: ['小说', '阿加莎'],
        status: 'buy'
    },
    {
        title: '藏书室女尸之谜',
        originaltitle: 'The Body in the Library',
        author: '阿加莎·克里斯蒂',
        date: '2013-05',
        rate: 7.4,
        img: 's26542141.jpg',
        no: 7,
        tags: ['小说', '阿加莎'],
        status: 'new'
    },
    {
        title: 'ABC谋杀案',
        originaltitle: 'The ABC Murders',
        author: '阿加莎·克里斯蒂',
        date: '2013-06',
        rate: 8.5,
        img: 's26716169.jpg',
        no: 8,
        tags: ['小说', '阿加莎'],
        status: 'buy'
    },
    {
        title: '底牌',
        originaltitle: 'Cards on the Table',
        author: '阿加莎·克里斯蒂',
        date: '2013-07',
        rate: 8.1,
        img: 's26841474.jpg',
        no: 9,
        tags: ['小说', '阿加莎'],
        status: 'buy'
    },
    {
        title: '无人生还',
        originaltitle: 'And Then There Were None',
        author: '阿加莎·克里斯蒂',
        date: '2013-07',
        rate: 8.7,
        img: 's26849345.jpg',
        no: 10,
        tags: ['小说', '阿加莎'],
        status: 'buy'
    },
    {
        title: '尼罗河上的惨案',
        originaltitle: 'Death on the Nile',
        author: '阿加莎·克里斯蒂',
        date: '2013-09',
        rate: 8.6,
        img: 's27027698.jpg',
        no: 11,
        tags: ['小说', '阿加莎'],
        status: 'buy'
    },
    {
        title: '人性记录',
        originaltitle: 'Lord Edgware Dies',
        author: '阿加莎·克里斯蒂',
        date: '2014-01',
        rate: 7.8,
        img: 's27201657.jpg',
        no: 12,
        tags: ['小说', '阿加莎'],
        status: 'new'
    },
    {
        title: '',
        originaltitle: '',
        author: '阿加莎·克里斯蒂',
        date: '2013-04',
        rate: 9.0,
        img: '.jpg',
        no: 13,
        tags: ['小说', '阿加莎'],
        status: 'new'
    },
    {
        title: '长夜',
        originaltitle: 'Endless Night',
        author: '阿加莎·克里斯蒂',
        date: '2014-04',
        rate: 8.1,
        img: 's27240561.jpg',
        no: 14,
        tags: ['小说', '阿加莎'],
        status: 'new'
    },
    {
        title: '怪屋',
        originaltitle: 'Crooked House',
        author: '阿加莎·克里斯蒂',
        date: '2014-05',
        rate: 7.7,
        img: 's27255818.jpg',
        no: 15,
        tags: ['小说', '阿加莎'],
        status: 'new'
    },
    {
        title: '',
        originaltitle: '',
        author: '阿加莎·克里斯蒂',
        date: '2013-04',
        rate: 9.0,
        img: '.jpg',
        no: 16,
        tags: ['小说', '阿加莎'],
        status: 'new'
    },
    {
        title: '古墓之谜',
        originaltitle: 'Murder in Mesopotamia',
        author: '阿加莎·克里斯蒂',
        date: '2014-06',
        rate: 7.5,
        img: 's27283286.jpg',
        no: 17,
        tags: ['小说', '阿加莎'],
        status: 'new'
    },
    {
        title: '沉默的证人',
        originaltitle: 'Dumb Witness',
        author: '阿加莎·克里斯蒂',
        date: '2014-06',
        rate: 7.4,
        img: 's27275152.jpg',
        no: 18,
        tags: ['小说', '阿加莎'],
        status: 'new'
    },
    {
        title: '高尔夫球场命案',
        originaltitle: 'The Murder on the Links',
        author: '阿加莎·克里斯蒂',
        date: '2014-07',
        rate: 8.1,
        img: 's27303201.jpg',
        no: 19,
        tags: ['小说', '阿加莎'],
        status: 'buy'
    },
    {
        title: '',
        originaltitle: '',
        author: '阿加莎·克里斯蒂',
        date: '2013-04',
        rate: 9.0,
        img: '.jpg',
        no: 20,
        tags: ['小说', '阿加莎'],
        status: 'new'
    },
    {
        title: '云中命案',
        originaltitle: 'Death in the Clouds',
        author: '阿加莎·克里斯蒂',
        date: '2014-07',
        rate: 7.2,
        img: 's27326126.jpg',
        no: 21,
        tags: ['小说', '阿加莎'],
        status: 'new'
    },
    {
        title: '阳光下的罪恶',
        originaltitle: 'Evil Under the Sun',
        author: '阿加莎·克里斯蒂',
        date: '2014-08',
        rate: 8.1,
        img: 's27327775.jpg',
        no: 22,
        tags: ['小说', '阿加莎'],
        status: 'new'
    },
    {
        title: '谋杀启事',
        originaltitle: 'A Murder is Announced',
        author: '阿加莎·克里斯蒂',
        date: '2014-08',
        rate: 7.8,
        img: 's27326123.jpg',
        no: 23,
        tags: ['小说', '阿加莎'],
        status: 'new'
    },
    {
        title: '死亡约会',
        originaltitle: 'Appointment With Death',
        author: '阿加莎·克里斯蒂',
        date: '2014-09',
        rate: 7.5,
        img: 's27410849.jpg',
        no: 24,
        tags: ['小说', '阿加莎'],
        status: 'new'
    },
    {
        title: '沉睡谋杀案',
        originaltitle: 'Sleeping Murder',
        author: '阿加莎·克里斯蒂',
        date: '2014-09',
        rate: 7.7,
        img: 's27445577.jpg',
        no: 25,
        tags: ['小说', '阿加莎'],
        status: 'new'
    },
    {
        title: '五只小猪',
        originaltitle: '',
        author: '阿加莎·克里斯蒂',
        date: '2014-10',
        rate: 8.5,
        img: 's27467193.jpg',
        no: 26,
        tags: ['小说', '阿加莎'],
        status: 'buy'
    },
    {
        title: '破镜谋杀案',
        originaltitle: 'The Mirror Crack’d from Side to Side',
        author: '阿加莎·克里斯蒂',
        date: '2014-10',
        rate: 7.6,
        img: 's27467312.jpg',
        no: 27,
        tags: ['小说', '阿加莎'],
        status: 'new'
    },
    {
        title: '空幻之屋',
        originaltitle: 'The Hollow',
        author: '阿加莎·克里斯蒂',
        date: '2014-11',
        rate: 7.7,
        img: 's27903133.jpg',
        no: 28,
        tags: ['小说', '阿加莎'],
        status: 'new'
    },
    {
        title: '',
        originaltitle: '',
        author: '阿加莎·克里斯蒂',
        date: '2013-04',
        rate: 9.0,
        img: '.jpg',
        no: 29,
        tags: ['小说', '阿加莎'],
        status: 'new'
    },
    {
        title: '葬礼之后',
        originaltitle: 'After the Funeral',
        author: '阿加莎·克里斯蒂',
        date: '2014-12',
        rate: 7.6,
        img: 's28353288.jpg',
        no: 30,
        tags: ['小说', '阿加莎'],
        status: 'buy'
    },
    {
        title: '',
        originaltitle: '',
        author: '阿加莎·克里斯蒂',
        date: '2013-04',
        rate: 9.0,
        img: '.jpg',
        no: 31,
        tags: ['小说', '阿加莎'],
        status: 'new'
    },
    {
        title: '',
        originaltitle: '',
        author: '阿加莎·克里斯蒂',
        date: '2013-04',
        rate: 9.0,
        img: '.jpg',
        no: 32,
        tags: ['小说', '阿加莎'],
        status: 'new'
    },
    {
        title: '帷幕',
        originaltitle: 'Curtain: Poirot s Last Case',
        author: '阿加莎·克里斯蒂',
        date: '2015-02',
        rate: 9.2,
        img: 's27988902.jpg',
        no: 33,
        tags: ['小说', '阿加莎', 'Top250'],
        status: 'new'
    },
    {
        title: '万圣节前夜的谋杀',
        originaltitle: 'Hallowe’en Party',
        author: '阿加莎·克里斯蒂',
        date: '2016-01',
        rate: 6.7,
        img: 's28373486.jpg',
        no: 40,
        tags: ['小说', '阿加莎'],
        status: 'new'
    },
    {
        title: '',
        originaltitle: '',
        author: '阿加莎·克里斯蒂',
        date: '2013-04',
        rate: 9.0,
        img: '.jpg',
        no: 41,
        tags: ['小说', '阿加莎'],
        status: 'new'
    },
    {
        title: '',
        originaltitle: '',
        author: '阿加莎·克里斯蒂',
        date: '2013-04',
        rate: 9.0,
        img: '.jpg',
        no: 42,
        tags: ['小说', '阿加莎'],
        status: 'new'
    },
    {
        title: '波洛圣诞探案记',
        originaltitle: 'Hercule Poirot s Christmas',
        author: '阿加莎·克里斯蒂',
        date: '2016-01',
        rate: 8.2,
        img: 's28375770.jpg',
        no: 43,
        tags: ['小说', '阿加莎'],
        status: 'new'
    },
    {
        title: '',
        originaltitle: '',
        author: '阿加莎·克里斯蒂',
        date: '2013-04',
        rate: 9.0,
        img: '.jpg',
        no: 44,
        tags: ['小说', '阿加莎'],
        status: 'new'
    },
    {
        title: '蓝色列车之谜',
        originaltitle: 'The Mystery of the Blue Train',
        author: '阿加莎·克里斯蒂',
        date: '2016-07',
        rate: 7.2,
        img: 's28837577.jpg',
        no: 45,
        tags: ['小说', '阿加莎'],
        status: 'new'
    },
    {
        title: '',
        originaltitle: '',
        author: '阿加莎·克里斯蒂',
        date: '2013-04',
        rate: 9.0,
        img: '.jpg',
        no: 46,
        tags: ['小说', '阿加莎'],
        status: 'new'
    },
    {
        title: '',
        originaltitle: '',
        author: '阿加莎·克里斯蒂',
        date: '2013-04',
        rate: 9.0,
        img: '.jpg',
        no: 47,
        tags: ['小说', '阿加莎'],
        status: 'new'
    },
    {
        title: '',
        originaltitle: '',
        author: '阿加莎·克里斯蒂',
        date: '2013-04',
        rate: 9.0,
        img: '.jpg',
        no: 48,
        tags: ['小说', '阿加莎'],
        status: 'new'
    },
    {
        title: '',
        originaltitle: '',
        author: '阿加莎·克里斯蒂',
        date: '2013-04',
        rate: 9.0,
        img: '.jpg',
        no: 49,
        tags: ['小说', '阿加莎'],
        status: 'new'
    },
    {
        title: '零点',
        originaltitle: 'Towards Zero',
        author: '阿加莎·克里斯蒂',
        date: '2016-11',
        rate: 8.2,
        img: 's29114831.jpg',
        no: 50,
        tags: ['小说', '阿加莎'],
        status: 'new'
    },
    {
        title: '',
        originaltitle: '',
        author: '阿加莎·克里斯蒂',
        date: '2013-04',
        rate: 9.0,
        img: '.jpg',
        no: 51,
        tags: ['小说', '阿加莎'],
        status: 'new'
    },
    {
        title: '牙医谋杀案',
        originaltitle: 'One,Two,Buckle My Shoe',
        author: '阿加莎·克里斯蒂',
        date: '2017-03',
        rate: 8.0,
        img: 's29344666.jpg',
        no: 52,
        tags: ['小说', '阿加莎'],
        status: 'new'
    },
    {
        title: '',
        originaltitle: '',
        author: '阿加莎·克里斯蒂',
        date: '2013-04',
        rate: 9.0,
        img: '.jpg',
        no: 53,
        tags: ['小说', '阿加莎'],
        status: 'new'
    },
    {
        title: '四魔头',
        originaltitle: 'The Big Four',
        author: '阿加莎·克里斯蒂',
        date: '2017-01',
        rate: 6.0,
        img: 's29183622.jpg',
        no: 54,
        tags: ['小说', '阿加莎'],
        status: 'new'
    },
    {
        title: '控方证人',
        originaltitle: 'The Witness for the Prosecution and Other Stories',
        author: '阿加莎·克里斯蒂',
        date: '2017-05',
        rate: 7.3,
        img: 's29432508.jpg',
        no: 55,
        tags: ['小说', '阿加莎'],
        status: 'buy'
    },
    {
        title: '三幕悲剧',
        originaltitle: 'Three Act Tragedy',
        author: '阿加莎·克里斯蒂',
        date: '2018-11',
        rate: 8.1,
        img: 's29904711.jpg',
        no: 64,
        tags: ['小说', '阿加莎'],
        status: 'new'
    },
    {
        title: 'H庄园的午餐',
        originaltitle: 'Sad Cypress',
        author: '阿加莎·克里斯蒂',
        date: '2018-01',
        rate: 7.9,
        img: 's29632157.jpg',
        no: 69,
        tags: ['小说', '阿加莎'],
        status: 'new'
    },
    {
        title: '',
        originaltitle: '',
        author: '阿加莎·克里斯蒂',
        date: '2013-04',
        rate: 9.0,
        img: '.jpg',
        no: 70,
        tags: ['小说', '阿加莎'],
        status: 'new'
    },
    {
        title: '清洁女工之死',
        originaltitle: 'Mrs McGinty s Dead',
        author: '阿加莎·克里斯蒂',
        date: '2018-04',
        rate: 7.3,
        img: 's29724949.jpg',
        no: 71,
        tags: ['小说', '阿加莎'],
        status: 'new'
    },
    {
        title: '',
        originaltitle: '',
        author: '阿加莎·克里斯蒂',
        date: '2013-04',
        rate: 9.0,
        img: '.jpg',
        no: 72,
        tags: ['小说', '阿加莎'],
        status: 'new'
    },
    {
        title: '死亡草',
        originaltitle: 'The Thirteen Problems',
        author: '阿加莎·克里斯蒂',
        date: '2018-07',
        rate: 8.1,
        img: 's29790378.jpg',
        no: 73,
        tags: ['小说', '阿加莎'],
        status: 'new'
    },
    {
        title: '黑麦奇案',
        originaltitle: 'A Pocket Full Of Rye',
        author: '阿加莎·克里斯蒂',
        date: '2018-04',
        rate: 7.7,
        img: 's29718837.jpg',
        no: 80,
        tags: ['小说', '阿加莎'],
        status: 'new'
    },
    {
        title: '首相绑架案',
        originaltitle: 'Poirot Investigates',
        author: '阿加莎·克里斯蒂',
        date: '2018-11',
        rate: 6.5,
        img: 's29926090.jpg',
        no: 81,
        tags: ['小说', '阿加莎'],
        status: 'new'
    },
    {
        title: '尼罗河上的惨案',
        originaltitle: 'Death on the Nile',
        author: '阿加莎·克里斯蒂',
        date: '2022-06',
        rate: 8.6,
        img: 's34281452.jpg',
        tags: ['小说'],
        status: 'buy'
    },
    {
        title: '',
        originaltitle: '',
        author: '',
        date: '2020-01',
        rate: 8.0,
        img: '123.jpg',
        tags: ['小说'],
        status: 'buy'
    },
]