export const list = [
    {
        name: '京都动画',
        another: '京阿尼',
        icon: '',
        datas: [
            {
                name: '全金属狂潮',
                poster: '',
                id: '0b63e49f55bc7c9b56b7e04571a8062f',
            },
            {
                name: 'AIR',
                poster: '',
                id: 'ab0128378818e161482042209f2c49cc',
            },
            { name: '凉宫春日的忧郁', poster: '', id: '', },
            { name: 'Kanon', poster: '', id: '', },
            { name: '幸运星', poster: '', id: '', },
            { name: 'CLANNAD', poster: '', id: '', },
            {
                name: '轻音少女',
                poster: '',
                id: '86b1902f6d5e391f3cbc7161e02745fa',
            },
            {
                name: '日常',
                poster: '日常.png',
                id: '',
            },
            {
                name: '冰菓',
                poster: '冰果.png',
                id: '',
            },
            { name: '中二病也要谈恋爱！', poster: '', id: '', },
            { name: '玉子市场', poster: '', id: '', },
            { name: 'Free!', poster: '', id: '', },
            { name: '境界的彼方', poster: '', id: '', },
            { name: '甘城光辉游乐园', poster: '', id: '', },
            { name: '吹响！上低音号', poster: '', id: '', },
            { name: '甘城光辉游乐园', poster: '', id: '', },
            { name: '无彩限的怪灵世界', poster: '', id: '', },
            { name: '小林家的龙女仆', poster: '', id: '', },
            { name: '甘城光辉游乐园', poster: '', id: '', },
            { name: '弦音 弓道部', poster: '', id: '', },
        ]
    },
    {
        name: 'Bones',
        another: '骨头社',
        icon: '',
        datas: [
            { name: '翼神传说', poster: '', id: '', },
            { name: '狼雨', poster: '', id: '', },
            { name: '钢之炼金术师', poster: '', id: '', },
            { name: '交响诗篇', poster: '', id: '', },
            { name: '樱兰高校男公关部', poster: '', id: '', },
            { name: '黑之契约者', poster: '', id: '', },
            { name: '噬魂师', poster: '', id: '', },
            { name: '钢之炼金术师FA', poster: '', id: '', },
            { name: '东京地震8.0', poster: '', id: '', },
            { name: '哥特萝莉侦探事件簿', poster: '', id: '', },
            { name: '未来都市No.6', poster: '', id: '', },
            { name: '因果日记', poster: '', id: '', },
            { name: '绝园的暴风雨', poster: '', id: '', },
            { name: '野良神', poster: '', id: '', },
            { name: '棺姬嘉依卡', poster: '', id: '', },
            { name: '血界战线', poster: '', id: '', },
            { name: '赤发白雪姬', poster: '', id: '', },
            { name: '文豪野犬', poster: '', id: '', },
            { name: '我的英雄学院', poster: '', id: '', },
            { name: '灵能百分百', poster: '', id: '', },
            { name: 'A.I.C.O. Incarnation', poster: '', id: '', },
            { name: '瓦尼塔斯的手记', poster: '', id: '', },
            { name: 'SK∞', poster: '', id: '', },
        ],
    },
    {
        name: 'Production I.G',
        another: '',
        icon: '',
        datas: [
            { name: '攻壳机动队', poster: '', id: '', },
            { name: 'BLOOD+', poster: '', id: '', },
            { name: 'xxxHOLiC', poster: '', id: '', },
            { name: '图书馆战争', poster: '', id: '', },
            { name: '战国BASARA', poster: '', id: '', },
            { name: '东之伊甸', poster: '', id: '', },
            { name: '好想告诉你', poster: '', id: '', },
            { name: '恶魔阿萨谢尔在召唤你', poster: '', id: '', },
            { name: 'BLOOD-C', poster: '', id: '', },
            { name: '白兔糖', poster: '', id: '', },
            { name: '罪恶王冠', poster: '', id: '', },
            { name: '勿忘蛛', poster: '', id: '', },
            { name: '新网球王子', poster: '', id: '', },
            { name: '黑子的篮球', poster: '', id: '', },
            { name: 'PSYCHO-PASS', poster: '', id: '', },
            { name: '机器人笔记', poster: '', id: '', },
            { name: '进击的巨人', poster: '', id: '', },
            { name: '翠星之加尔刚蒂亚', poster: '', id: '', },
            { name: '钻石王牌', poster: '', id: '', },
            { name: '排球少年', poster: '', id: '', },
            { name: '代号D机关', poster: '', id: '', },
            { name: '强风吹拂', poster: '', id: '', },
            { name: '机动奥特曼', poster: '', id: '', },
            { name: '忧国的莫里亚蒂', poster: '', id: '', },
            { name: '天国大魔境', poster: '', id: '', },
            { name: '怪兽8号', poster: '', id: '', },
        ],
    },
    {
        name: 'Madhouse',
        another: '疯房子',
        icon: '',
        datas: [
            { name: '枪神', poster: '', id: '', },
            { name: '魔卡少女樱', poster: '', id: '', },
            { name: '人型电脑天使心', poster: '', id: '', },
            { name: '铳墓', poster: '', id: '', },
            { name: '妄想代理人', poster: '', id: '', },
            { name: 'MONSTER', poster: '', id: '', },
            { name: '斗牌传说', poster: '', id: '', },
            { name: 'NANA', poster: '', id: '', },
            { name: '黑礁', poster: '', id: '', },
            { name: '死亡笔记', poster: '', id: '', },
            { name: '大剑', poster: '', id: '', },
            { name: '鬼泣', poster: '', id: '', },
            { name: '电脑线圈', poster: '', id: '', },
            { name: '赌博默示录', poster: '', id: '', },
            { name: '青之文学', poster: '', id: '', },
            { name: '四叠半神话大系', poster: '', id: '', },
            { name: '学园默示录', poster: '', id: '', },
            { name: '全职猎人', poster: '', id: '', },
            { name: '魔法少女小圆', poster: '', id: '', },
            { name: '花牌情缘', poster: '', id: '', },
            { name: '惊爆游戏', poster: '', id: '', },
            { name: '钻石王牌', poster: '', id: '', },
            { name: '神不在的星期天', poster: '', id: '', },
            { name: '游戏人生', poster: '', id: '', },
            { name: '寄生兽', poster: '', id: '', },
            { name: '死亡游行', poster: '', id: '', },
            { name: 'OVERLORD', poster: '', id: '', },
            { name: '一拳超人', poster: '', id: '', },
            { name: '比宇宙更远的地方', poster: '', id: '', },
            { name: '不吉波普不笑', poster: '', id: '', },
            { name: '漂流少年', poster: '', id: '', },
        ],
    },
    {
        name: 'MAPPA',
        another: '',
        icon: '',
        datas: [
            { name: '狂赌之渊', poster: '', id: '', },
            { name: '咒术廻战', poster: '', id: '', },
            {
                name: '电锯人',
                poster: '电锯人.png',
                id: 'a51209628675af2736c039f8538ffb9d',
            },
            {
                name: '地狱乐',
                poster: '地狱乐.png',
                id: 'fad8858db7c6229bc32fcad715653d62',
            },
        ],
    },
    {
        name: 'ufotable',
        another: '飞碟社',
        icon: '',
        datas: [
            { name: '空之境界', poster: '', id: '', },
            { name: 'Fate', poster: '', id: '', },
            { name: '鬼灭之刃', poster: '', id: '', },
            { name: '东京食尸鬼', poster: '', id: '', },
            { name: '阿松', poster: '', id: '', },
        ],
    },
    {
        name: 'SUNRISE',
        another: '日昇',
        icon: '',
        datas: [
            { name: '高达', poster: '', id: '', },
            { name: '城市猎人', poster: '', id: '', },
            { name: '高智能方程式', poster: '', id: '', },
            { name: '犬夜叉', poster: '', id: '', },
            { name: '银魂', poster: '', id: '', },
            { name: '反叛的鲁路修', poster: '', id: '', },
            { name: 'Keroro军曹', poster: '', id: '', },
            { name: 'LoveLive!', poster: '', id: '', },
        ],
    },
    {
        name: 'WIT STUDIO',
        another: '霸权社',
        icon: '',
        datas: [
            { name: '进击的巨人', poster: '', id: '', },
            { name: '鬼灯的冷彻', poster: '', id: '', },
            { name: '魔法使的新娘', poster: '', id: '', },
            { name: 'GREAT PRETENDER', poster: '', id: '', },
            { name: '国王排名', poster: '', id: '', },
            { name: 'SPY×FAMILY', poster: '', id: '', },
        ],
    },
    {
        name: 'A-1 Pictures',
        another: '',
        icon: '',
        datas: [
            { name: '黑执事', poster: '', id: '', },
            { name: '妖精的尾巴', poster: '', id: '', },
            { name: '未闻花名', poster: '', id: '', },
            { name: '偶像大师', poster: '', id: '', },
            { name: '刀剑神域', poster: '', id: '', },
            { name: 'MAGI魔奇少年', poster: '', id: '', },
            { name: '四月是你的谎言', poster: '', id: '', },
            { name: '埃罗芒阿老师', poster: '', id: '', },
            { name: '七大罪', poster: '', id: '', },
            { name: '辉夜姬想让人告白', poster: '', id: '', },
            { name: '催眠麦克风', poster: '', id: '', },
            { name: '86－不存在的战区－', poster: '', id: '', },
            { name: '视觉监狱', poster: '', id: '', },
            { name: '莉可丽丝', poster: '', id: '', },
        ],
    },
    {
        name: 'Pierrot',
        another: '小丑社',
        icon: '',
        datas: [
            { name: '幽☆游☆白书', poster: '', id: '', },
            { name: '麻辣教师GTO', poster: '', id: '', },
            { name: '棋魂', poster: '', id: '', },
            { name: '火影忍者', poster: '', id: '', },
            { name: '最游记', poster: '', id: '', },
            { name: '死神', poster: '', id: '', },
            { name: '王者天下', poster: '', id: '', },
            { name: '东京喰种', poster: '', id: '', },
            { name: '黑色五叶草', poster: '', id: '', },
            { name: '阿松', poster: '', id: '', },
            { name: '福星小子', poster: '', id: '', },
        ],
    },
    {
        name: 'SHAFT',
        another: '沙发套',
        icon: '',
        datas: [
            { name: '魔法少女小圆', poster: '', id: '', },
        ],
    },
    {
        name: 'J.C.STAFF',
        another: '节操社',
        icon: '',
        datas: [
            { name: '龙与虎', poster: '', id: '', },
            { name: '魔法禁书目录', poster: '', id: '', },
            { name: '某科学的超电磁炮', poster: '', id: '', },
            { name: '爆漫王', poster: '', id: '', },
            { name: '爱杀宝贝', poster: '', id: '', },
            { name: '食戟之灵', poster: '', id: '', },
            { name: '下流梗不存在的灰暗世界', poster: '', id: '', },
            { name: '高分少女', poster: '', id: '', },
            { name: '极主夫道', poster: '', id: '', },
            { name: '齐木楠雄的灾难', poster: '', id: '', },
        ],
    },
    {
        name: 'P.A.WORKS',
        another: '',
        icon: '',
        datas: [
            { name: '真实之泪', poster: '', id: '', },
            { name: '花开伊吕波', poster: '', id: '', },
            { name: 'TARI TARI', poster: '', id: '', },
            { name: 'Angel Beats！', poster: '', id: '', },
            { name: 'Charlotte', poster: '', id: '', },
            { name: '成神之日', poster: '', id: '', },
            { name: '白箱', poster: '', id: '', },
            { name: '樱花任务', poster: '', id: '', },
        ],
    },
    {
        name: '动画工房',
        another: '',
        icon: '',
        datas: [
            { name: '药师寺凉子的怪奇事件簿', poster: '', id: '', },
            { name: '摇曳百合', poster: '', id: '', },
            { name: '月刊少女野崎君', poster: '', id: '', },
            { name: '干物妹！小埋', poster: '', id: '', },
            { name: '绯弹的亚里亚', poster: '', id: '', },
            { name: '我推的孩子', poster: '', id: '', },
        ],
    },
    {
        name: 'TRIGGER',
        another: '扳机社',
        icon: '',
        datas: [
            { name: 'DARLING in the FRANXXX', poster: '', id: '', },
            { name: '普罗米亚', poster: '', id: '', },
            { name: '电光超人古立特', poster: '', id: '', },
            { name: '电光机王', poster: '', id: '', },
            { name: '赛博朋克', poster: '', id: '', },
        ],
    },
    {
        name: 'xxx',
        another: '',
        icon: '',
        datas: [
            { name: 'xxx', poster: '', id: '', },
        ],
    },
]