/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('antdv-next')['Button']
    ACheckbox: typeof import('antdv-next')['Checkbox']
    ACheckboxGroup: typeof import('antdv-next')['CheckboxGroup']
    ADatePicker: typeof import('antdv-next')['DatePicker']
    ADropdown: typeof import('antdv-next')['Dropdown']
    AForm: typeof import('antdv-next')['Form']
    AFormItem: typeof import('antdv-next')['FormItem']
    AInput: typeof import('antdv-next')['Input']
    AInputNumber: typeof import('antdv-next')['InputNumber']
    AInputPassword: typeof import('antdv-next')['InputPassword']
    ALayout: typeof import('antdv-next')['Layout']
    ALayoutContent: typeof import('antdv-next')['LayoutContent']
    ALayoutHeader: typeof import('antdv-next')['LayoutHeader']
    AMenu: typeof import('antdv-next')['Menu']
    AMenuItem: typeof import('antdv-next')['MenuItem']
    AModal: typeof import('antdv-next')['Modal']
    ARadio: typeof import('antdv-next')['Radio']
    ARadioGroup: typeof import('antdv-next')['RadioGroup']
    ARangePicker: typeof import('antdv-next')['DateRangePicker']
    ASelect: typeof import('antdv-next')['Select']
    ASelectOption: typeof import('antdv-next')['SelectOption']
    ASlider: typeof import('antdv-next')['Slider']
    ASpace: typeof import('antdv-next')['Space']
    ASubMenu: typeof import('antdv-next')['SubMenu']
    ASwitch: typeof import('antdv-next')['Switch']
    ATextarea: typeof import('antdv-next')['TextArea']
    ATooltip: typeof import('antdv-next')['Tooltip']
    AUpload: typeof import('antdv-next')['Upload']
    AUploadDragger: typeof import('antdv-next')['UploadDragger']
    Bgs: typeof import('./src/components/bgs.vue')['default']
    Contents: typeof import('./src/components/layouts/contents.vue')['default']
    Layout: typeof import('./src/components/layouts/layout.vue')['default']
    LayoutPlatform: typeof import('./src/components/layouts/layout-platform.vue')['default']
    LayoutThree: typeof import('./src/components/layouts/layout-three.vue')['default']
    MenuItem: typeof import('./src/components/layouts/menu-item.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Using: typeof import('./src/components/chats/using.vue')['default']
    View: typeof import('./src/components/chats/view.vue')['default']
  }
}
