export const ports = [
  {
    category: "网络与基础通信类",
    list: [
      {
        name: "FTP 数据",
        full: "File Transfer Protocol Data",
        port: "20",
        icon: "wifi",
        type: "TCP",
      },
      {
        name: "FTP 控制",
        full: "File Transfer Protocol Control",
        port: "21",
        icon: "wifi",
        type: "TCP",
      },
      {
        name: "FTPS",
        full: "FTP Secure",
        port: "990",
        icon: "wifi",
        type: "TCP",
      },
      {
        name: "SSH",
        full: "Secure Shell",
        port: "22",
        icon: "wifi",
        type: "TCP",
      },
      {
        name: "Telnet",
        full: "明文远程登录协议",
        port: "23",
        icon: "wifi",
        type: "TCP",
      },
      {
        name: "SMTP",
        full: "Simple Mail Transfer Protocol",
        port: "25",
        icon: "envelope",
        type: "TCP",
      },
      {
        name: "SMTPS",
        full: "SMTP over SSL",
        port: "465",
        icon: "envelope",
        type: "TCP",
      },
      {
        name: "Submission",
        full: "现代 SMTP 提交端口",
        port: "587",
        icon: "envelope",
        type: "TCP",
      },
      {
        name: "HTTP",
        full: "HyperText Transfer Protocol",
        port: "80",
        icon: "wifi",
        type: "TCP",
      },
      {
        name: "HTTPS",
        full: "HTTP Secure",
        port: "443",
        icon: "wifi",
        type: "TCP",
      },
      {
        name: "POP3",
        full: "Post Office Protocol v3",
        port: "110",
        icon: "envelope",
        type: "TCP",
      },
      {
        name: "POP3S",
        full: "POP3 over SSL",
        port: "995",
        icon: "envelope",
        type: "TCP",
      },
      {
        name: "IMAP",
        full: "Internet Message Access Protocol",
        port: "143",
        icon: "envelope",
        type: "TCP",
      },
      {
        name: "IMAPS",
        full: "IMAP over SSL",
        port: "993",
        icon: "envelope",
        type: "TCP",
      },
      {
        name: "SOCKS 代理",
        full: "通用代理传输协议",
        port: "1080",
        icon: "wifi",
        type: "TCP",
      },
      {
        name: "SMB",
        full: "Server Message Block",
        port: "445",
        icon: "wifi",
        type: "TCP",
      },
      {
        name: "LDAP",
        full: "Lightweight Directory Access Protocol",
        port: "389",
        icon: "wifi",
        type: "TCP",
      },
      {
        name: "LDAPS",
        full: "LDAP over SSL/TLS",
        port: "636",
        icon: "wifi",
        type: "TCP",
      },
      {
        name: "RPC",
        full: "Remote Procedure Call",
        port: "135",
        icon: "wifi",
        type: "TCP",
      },
      {
        name: "DNS",
        full: "Domain Name System",
        port: "53",
        icon: "wifi",
        type: "UDP",
      },
      {
        name: "DHCP 服务端",
        full: "为客户端分配 IP 地址",
        port: "67",
        icon: "wifi",
        type: "UDP",
      },
      {
        name: "DHCP 客户端",
        full: "Dynamic Host Configuration Protocol",
        port: "68",
        icon: "wifi",
        type: "UDP",
      },
      {
        name: "TFTP",
        full: "Trivial File Transfer Protocol",
        port: "69",
        icon: "wifi",
        type: "UDP",
      },
      {
        name: "SNMP",
        full: "Simple Network Management Protocol",
        port: "161/162",
        icon: "wifi",
        type: "TCP",
      },
    ],
  },
  {
    category: "数据库类",
    list: [
      {
        name: "MySQL",
        full: "MySQL Database Server",
        port: "3306",
        icon: "database",
        type: "TCP",
      },
      {
        name: "PostgreSQL",
        full: "PostgreSQL",
        port: "5432",
        icon: "database",
        type: "TCP",
      },
      {
        name: "Oracle",
        full: "Oracle Net Listener",
        port: "1521",
        icon: "database",
        type: "TCP",
      },
      {
        name: "MS SQL",
        full: "Microsoft SQL Server",
        port: "1433",
        icon: "database",
        type: "TCP",
      },
      {
        name: "SQL Server Browser",
        full: "数据库实例发现服务",
        port: "1434",
        icon: "database",
        type: "TCP",
      },
      {
        name: "MongoDB",
        full: "MongoDB",
        port: "27017",
        icon: "database",
        type: "TCP",
      },
      {
        name: "Redis",
        full: "In-memory Key-Value Database",
        port: "6379",
        icon: "database",
        type: "TCP",
      },
      {
        name: "Elasticsearch",
        full: "REST API 端口",
        port: "9200",
        icon: "database",
        type: "TCP",
      },
      {
        name: "Cassandra",
        full: "Cassandra Native Transport",
        port: "9042",
        icon: "database",
        type: "TCP",
      },
      {
        name: "Neo4j",
        full: "图数据库",
        port: "7474",
        icon: "database",
        type: "TCP",
      },
      {
        name: "InfluxDB",
        full: "时序数据库",
        port: "8086",
        icon: "database",
        type: "TCP",
      },
    ],
  },
  {
    category: "安全与远程管理类",
    list: [
      {
        name: "RDP",
        full: "Remote Desktop Protocol",
        port: "3389",
        icon: "wifi",
        type: "TCP",
      },
      {
        name: "VNC",
        full: "Virtual Network Computing",
        port: "5900",
        icon: "wifi",
        type: "TCP",
      },
    ],
  },
];
