export const characters = [
    { name: '孙悟空 少年', img: 'sunwukong.png' },
    { name: '卡卡罗特', img: 'kakarotto.png' },
    { name: '卡卡罗特 超赛', img: 'kakarotto1.png' },
    { name: '卡卡罗特 超赛2', img: 'kakarotto2.png' },
    { name: '卡卡罗特 超赛3', img: 'kakarotto3.png' },
    { name: '卡卡罗特 超赛4', img: 'kakarotto4.png' },
    { name: '卡卡罗特 超赛蓝', img: 'kakarotto_blue.png' },
    { name: '卡卡罗特 超赛红', img: 'kakarotto_red.png' },
    { name: '卡卡罗特 自在极意', img: 'kakarotto_zizai.png' },
    { name: '孙悟饭', img: 'songohan.png' },
    { name: '孙悟饭', img: 'songohan_2.png' },
    { name: '孙悟饭', img: 'songohan_3.png' },
    { name: '孙悟饭 超赛', img: 'songohan1.png' },
    { name: '孙悟饭 超赛2', img: 'songohan2.png' },
    { name: '孙悟饭', img: 'songohan_big.png' },
    { name: '孙悟饭 超赛', img: 'songohan_big1.png' },
    { name: '比迪丽', img: 'videl.png' },
    { name: '比迪丽', img: 'videl_short.png' },
    { name: '小芳', img: 'pan.png' },
    //
    { name: '贝吉塔', img: 'vegeta.png' },
    { name: '贝吉塔 超赛', img: 'vegeta1.png' },
    { name: '贝吉塔 魔人', img: 'vegeta_m.png' },
    { name: '贝吉塔 超赛蓝', img: 'vegeta_blue.png' },
    { name: '特兰克斯', img: 'trunks.png' },
    { name: '特兰克斯 超赛', img: 'trunks1.png' },
    { name: '特兰克斯 未来', img: 'trunks_old.png' },
    { name: '特兰克斯 超赛', img: 'trunks_old1.png' },
    //
    { name: '贝吉特', img: 'beijite.png' },
    { name: '贝吉特 超赛', img: 'beijite1.png' },
    { name: '贝吉特 超赛蓝', img: 'beijite_blue.png' },
    { name: '悟吉塔', img: 'wujita.png' },
    { name: '悟吉塔 超赛', img: 'wujita1.png' },
    { name: '悟吉塔 超赛4', img: 'wujita4.png' },
    { name: '悟吉塔 超赛蓝', img: 'wujita_blue.png' },
    { name: '悟天克斯', img: 'wutiankesi.png' },
    { name: '悟天克斯 超赛', img: 'wutiankesi1.png' },
    { name: '悟天克斯 超赛3', img: 'wutiankesi3.png' },
    // 友人
    { name: '琪琪', img: 'qiqi.png' },
    { name: '布玛', img: 'bulma.png' },
    { name: '武天', img: 'master.png' },
    { name: '克林', img: 'krillin.png' },
    { name: '比克', img: 'piccolo.png' },
    { name: '天津饭', img: 'tien.png' },
    { name: '饺子', img: 'jiaozi.png' },
    { name: '饮茶', img: 'yincha.png' },
    { name: '乌普', img: 'wupu.png' },
    // 神
    { name: '占卜婆婆', img: 'zhabu.png' },
    { name: '北界王', img: 'jiewang_north.png' },
    { name: '西界王', img: 'jiewang_west.png' },
    { name: '东界王', img: 'xx.png' },
    { name: '南界王', img: 'xx.png' },
    { name: '大界王', img: 'jiewang_big.png' },
    { name: '东界王神', img: 'jiewang_xin.png' },
    { name: '杰比特', img: 'jiewang_jiebite.png' },
    //
    { name: '炒饭', img: 'chaofan.png' },
    // 娜美克星
    { name: '弗利萨 一形', img: 'frieza1.png' },
    { name: '弗利萨 二形', img: 'frieza2.png' },
    { name: '弗利萨 三形', img: 'frieza3.png' },
    { name: '弗利萨 最终', img: 'frieza4.png' },
    { name: '弗利萨 机械', img: 'frieza_metal.png' },
    { name: '库尔德王', img: 'cold.png' },
    // 人造人篇
    { name: '人造人16号', img: '16.png' },
    { name: '人造人17号', img: '17.png' },
    { name: '人造人18号', img: '18.png' },
    { name: '人造人19号', img: '19.png' },
    { name: '西鲁 蛹', img: 'xilu_yong.png' },
    { name: '西鲁 一阶', img: 'xilu.png' },
    { name: '西鲁 二阶', img: 'xilu2.png' },
    { name: '西鲁 完全体', img: 'xilu3.png' },
    // 布欧篇
    { name: '巴比迪', img: 'babidi.png' },
    { name: '布欧', img: 'buou.png' },
    { name: '布欧 恶', img: 'buou_show.png' },
    { name: '布欧 大', img: 'buou_big.png' },
    { name: '布欧 小', img: 'buou_small.png' },
]