export const list = [
    { title: "游戏库", path: 'stores', img: 'switch.jpg' },
    { title: "动漫", path: 'cartoons', img: 'cartoon.png' },
    { title: "书架", path: 'books', img: 'books.jpg' },
    { title: "宝可梦", path: 'pokes', img: 'pokemon.png' },
    { title: "怪猎物语2", path: 'mhs2', img: 'mhs2.png' },
    { title: "动物森友会", path: 'animals', img: 'animal.png' },
    { title: "龙珠", path: 'dragon', img: 'dragonball.jpeg' },
    { title: "假面骑士", path: 'icons', img: 'riders.jpg' },
    { title: "F1 & Car", path: 'list/f1', img: 'f1.jpg' },
    { title: "英雄联盟", path: 'list/lol', img: 'lol.jpg' },
    { title: "Dota2", path: 'list/dota2', img: 'dota2.jpg' },
    { title: "CS GO", path: 'list/csgo', img: 'csgo.jpg' },
    { title: "M-League", path: 'list/majiang', img: 'majiang.jpg' },
    { title: "公司", path: 'list/company', img: 'company.jpg' },
]