/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACheckbox: typeof import('ant-design-vue/es')['Checkbox']
    ACheckboxGroup: typeof import('ant-design-vue/es')['CheckboxGroup']
    ADatePicker: typeof import('ant-design-vue/es')['DatePicker']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputNumber: typeof import('ant-design-vue/es')['InputNumber']
    AInputPassword: typeof import('ant-design-vue/es')['InputPassword']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    AModal: typeof import('ant-design-vue/es')['Modal']
    APopover: typeof import('ant-design-vue/es')['Popover']
    ARadio: typeof import('ant-design-vue/es')['Radio']
    ARadioGroup: typeof import('ant-design-vue/es')['RadioGroup']
    ARangePicker: typeof import('ant-design-vue/es')['RangePicker']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASelectOption: typeof import('ant-design-vue/es')['SelectOption']
    ASubMenu: typeof import('ant-design-vue/es')['SubMenu']
    ASwitch: typeof import('ant-design-vue/es')['Switch']
    ATextarea: typeof import('ant-design-vue/es')['Textarea']
    Barcode: typeof import('./components/barcode/barcode.vue')['default']
    Contents: typeof import('./components/layouts/contents.vue')['default']
    Layout: typeof import('./components/layouts/layout.vue')['default']
    LayoutPlatform: typeof import('./components/layouts/layout-platform.vue')['default']
    LayoutThree: typeof import('./components/layouts/layout-three.vue')['default']
    MenuItem: typeof import('./components/layouts/menu-item.vue')['default']
    Post: typeof import('./components/editor-code/post.vue')['default']
    Qrcode: typeof import('./components/barcode/qrcode.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Using: typeof import('./components/articles/using.vue')['default']
    View: typeof import('./components/articles/view.vue')['default']
    ViewTresjs: typeof import('./components/threejs/view-tresjs.vue')['default']
    WordCard: typeof import('./components/articles/wordCard.vue')['default']
    WordTip: typeof import('./components/articles/wordTip.vue')['default']
  }
}
