/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACarousel: typeof import('ant-design-vue/es')['Carousel']
    ACheckbox: typeof import('ant-design-vue/es')['Checkbox']
    ACheckboxGroup: typeof import('ant-design-vue/es')['CheckboxGroup']
    ADatePicker: typeof import('ant-design-vue/es/date-picker/dayjs')['default']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputNumber: typeof import('ant-design-vue/es')['InputNumber']
    AInputPassword: typeof import('ant-design-vue/es')['InputPassword']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    AModal: typeof import('ant-design-vue/es')['Modal']
    APopover: typeof import('ant-design-vue/es')['Popover']
    ARadio: typeof import('ant-design-vue/es')['Radio']
    ARadioGroup: typeof import('ant-design-vue/es')['RadioGroup']
    ARangePicker: typeof import('ant-design-vue/es/date-picker/dayjs')['RangePicker']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASelectOption: typeof import('ant-design-vue/es')['SelectOption']
    ASubMenu: typeof import('ant-design-vue/es')['SubMenu']
    ASwitch: typeof import('ant-design-vue/es')['Switch']
    ATextarea: typeof import('ant-design-vue/es')['Textarea']
    Barcode: typeof import('./components/barcode/barcode.vue')['default']
    Bgs: typeof import('./components/bgs.vue')['default']
    Contents: typeof import('./components/layouts/contents.vue')['default']
    Desktop: typeof import('./components/os/desktop.vue')['default']
    Drag: typeof import('./components/others/drag.vue')['default']
    Flip: typeof import('./components/flips/flip.vue')['default']
    Flows: typeof import('./components/workflows/flows.vue')['default']
    FlowsConfigs: typeof import('./components/workflows/flows-configs.vue')['default']
    FlowsNode: typeof import('./components/workflows/flows-node.vue')['default']
    Gasp: typeof import('./components/others/gasp.vue')['default']
    Group: typeof import('./components/flips/group.vue')['default']
    Layout: typeof import('./components/layouts/layout.vue')['default']
    LayoutPlatform: typeof import('./components/layouts/layout-platform.vue')['default']
    LayoutThree: typeof import('./components/layouts/layout-three.vue')['default']
    MenuItem: typeof import('./components/layouts/menu-item.vue')['default']
    Post: typeof import('./components/editor-code/post.vue')['default']
    Qrcode: typeof import('./components/barcode/qrcode.vue')['default']
    Roller: typeof import('./components/flips/roller.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Style: typeof import('./components/others/style.vue')['default']
    TimeSlide: typeof import('./components/gantt/time-slide.vue')['default']
    Using: typeof import('./components/annotations/using.vue')['default']
    View: typeof import('./components/annotations/view.vue')['default']
    Window: typeof import('./components/os/window.vue')['default']
    WordCard: typeof import('./components/articles/wordCard.vue')['default']
    WordTip: typeof import('./components/articles/wordTip.vue')['default']
  }
}
