export const items = [
    { name: '傅达', img: 'AC_Blathers.png', game: '集合啦！动物森友会', series: '动物森友会' },
    { name: '傅珂', img: 'AC_Celeste.png', game: '集合啦！动物森友会', series: '动物森友会' },
    { name: '', img: 'AC_Cyrrus.png', game: '集合啦！动物森友会', series: '动物森友会' },
    { name: '', img: 'AC_Digby.png', game: '集合啦！动物森友会', series: '动物森友会' },
    { name: '西施惠 夏装', img: 'AC_Isabelle (Summer Outfit).png', game: '集合啦！动物森友会', series: '动物森友会' },
    { name: '西施惠 冬装', img: 'AC_Isabelle.png', game: '集合啦！动物森友会', series: '动物森友会' },
    { name: 'K.K.', img: 'AC_K.K. Slider.png', game: '集合啦！动物森友会', series: '动物森友会' },
    { name: '', img: 'AC_Kappn.png', game: '集合啦！动物森友会', series: '动物森友会' },
    { name: '', img: 'AC_Kicks.png', game: '集合啦！动物森友会', series: '动物森友会' },
    { name: '', img: 'AC_Lottie.png', game: '集合啦！动物森友会', series: '动物森友会' },
    { name: '', img: 'AC_Mabel.png', game: '集合啦！动物森友会', series: '动物森友会' },
    { name: '', img: 'AC_Reese.png', game: '集合啦！动物森友会', series: '动物森友会' },
    { name: '', img: 'AC_Resetti.png', game: '集合啦！动物森友会', series: '动物森友会' },
    { name: '', img: 'AC_Rover.png', game: '集合啦！动物森友会', series: '动物森友会' },
    { name: '', img: 'AC_Timmy & Tommy.png', game: '集合啦！动物森友会', series: '动物森友会' },
    { name: '', img: 'AC_Tom Nook.png', game: '集合啦！动物森友会', series: '动物森友会' },
    { name: 'Qbby', img: 'BB_BoxBoy.jpg', game: '盒子男孩', series: '' },
    { name: '', img: 'CR_Chibi Robo.png', game: 'Chibi-Robo!', series: '' },
    { name: '', img: 'Diablo3_Loot Goblin.png', game: '暗黑破坏神3', series: '暗黑破坏神' },
    { name: '咚奇刚与宝琳', img: 'DK_咚奇刚与波琳.jpg', game: '咚奇刚 蕉力全开', series: '咚奇刚' },
    { name: '名侦探皮卡丘', img: 'DP_名侦探皮卡丘.jpg', game: '名侦探皮卡丘', series: '宝可梦' },
    { name: '太阳骑士索拉尔', img: 'DS_太阳骑士索拉尔.jpg', game: '太阳骑士索拉尔', series: '黑暗之魂' },
    { name: '赛莉卡', img: 'FE_Celica.jpg', game: '火焰纹章', series: '火焰纹章' },
    { name: '阿鲁姆', img: 'FE_Alm.jpg', game: '火焰纹章', series: '火焰纹章' },
    { name: '库洛姆', img: 'FE_Chrom.jpg', game: '火焰纹章', series: '火焰纹章' },
    { name: '琪姬', img: 'FE_Tiki.jpg', game: '火焰纹章', series: '火焰纹章' },
    { name: '帝帝帝大王', img: 'Kirby_King Dedede.jpg', game: '星之卡比', series: '卡比' },
    { name: '卡比', img: 'Kirby_Kirby.jpg', game: '星之卡比', series: '卡比' },
    { name: '魅塔骑士', img: 'Kirby_Meta Knight.jpg', game: '星之卡比', series: '卡比' },
    { name: '瓦豆鲁迪', img: 'Kirby_Waddle Dee.jpg', game: '星之卡比', series: '卡比' },
    { name: '', img: 'Metroid_萨姆斯·阿兰.jpg', game: '', series: '密特罗德' },
    { name: '', img: 'MD_E.M.M.I..jpg', game: '', series: '密特罗德' },
    { name: '', img: 'MD_生存恐惧萨姆斯.jpg', game: '', series: '密特罗德' },
    { name: '', img: 'Metroid_密特罗德.jpg', game: '', series: '密特罗德' },
    { name: '随从艾露猫', img: 'MHR_随从艾露猫.jpg', game: '', series: '怪物猎人' },
    { name: '随从牙猎犬', img: 'MHR_随从牙猎犬.jpg', game: '', series: '怪物猎人' },
    { name: '怨虎龙', img: 'MHR_怨虎龙.jpg', game: '', series: '怪物猎人' },
    { name: '爵银龙猫', img: 'MHRS_爵银龙猫.jpg', game: '', series: '怪物猎人' },
    { name: '爵银龙犬', img: 'MHRS_爵银龙犬.jpg', game: '', series: '怪物猎人' },
    { name: '爵银龙', img: 'MHRS_爵银龙.jpg', game: '', series: '怪物猎人' },
    { name: '', img: 'MHST_冰牙龙与亚尤利娅.jpg', game: '', series: '怪物猎人' },
    { name: '', img: 'MHST_彩鸟与丹前辈.jpg', game: '', series: '怪物猎人' },
    { name: '', img: 'MHST_雌火龙与修瓦尔.jpg', game: '', series: '怪物猎人' },
    { name: '', img: 'MHST_独眼雄火龙与男骑士.jpg', game: '', series: '怪物猎人' },
    { name: '', img: 'MHST_独眼雄火龙与女骑士.jpg', game: '', series: '怪物猎人' },
    { name: '', img: 'MHST_纳比尔.jpg', game: '', series: '怪物猎人' },
    { name: '', img: 'MHST2_艾娜.jpg', game: '', series: '怪物猎人' },
    { name: '', img: 'MHST2_毁灭火龙.jpg', game: '', series: '怪物猎人' },
    { name: '', img: 'MHST2_月露.jpg', game: '', series: '怪物猎人' },
    { name: '', img: 'MM_洛克人.jpg', game: '', series: '洛克人' },
    { name: '', img: 'Pikmin_皮克敏.jpg', game: '', series: '皮克敏' },
    { name: '卢克', img: 'SF6_卢克.jpg', game: '', series: '街头霸王' },
    { name: '杰米', img: 'SF6_杰米.jpg', game: '', series: '街头霸王' },
    { name: '金柏莉', img: 'SF6_金柏莉.jpg', game: '', series: '街头霸王' },
    { name: '', img: 'Sky_Donkey Kong.png', game: '', series: '' },
    { name: '', img: 'Sky_Dark Donkey Kong.png', game: '', series: '' },
    { name: '', img: 'Sky_Bowser.png', game: '', series: '' },
    { name: '', img: 'Sky_Dark Bowser.png', game: '', series: '' },
    { name: '马力欧', img: 'SM_Mario.png', game: '', series: '马力欧' },
    { name: '马力欧 银色', img: 'SM_Mario - Silver.png', game: '', series: '马力欧' },
    { name: '马力欧 金色', img: 'SM_Mario - Gold.png', game: '', series: '马力欧' },
    { name: '马力欧 经典色', img: 'SM_Mario Classic Color.png', game: '', series: '马力欧' },
    { name: '马力欧 现代色', img: 'SM_Mario Modern Color.png', game: '', series: '马力欧' },
    { name: '路易吉', img: 'SM_Luigi.jpg', game: '', series: '马力欧' },
    { name: '猫咪马力欧', img: 'SM_Cat Mario.jpg', game: '', series: '马力欧' },
    { name: '碧姬公主', img: 'SM_Peach.jpg', game: '', series: '马力欧' },
    { name: '猫咪碧姬公主', img: 'SM_Cat Peach.jpg', game: '', series: '马力欧' },
    { name: '罗洁塔', img: 'SM_Rosalina.jpg', game: '', series: '马力欧' },
    { name: '奇诺比奥', img: 'SM_Toad.png', game: '', series: '马力欧' },
    { name: '黛西公主', img: 'SM_Daisy.jpg', game: '', series: '马力欧' },
    { name: '咚奇刚', img: 'SM_Donkey Kong.jpg', game: '', series: '马力欧' },
    { name: '迪迪', img: 'SM_Diddy Kong.png', game: '', series: '马力欧' },
    { name: '酷霸王', img: 'SM_Bowser.png', game: '', series: '马力欧' },
    { name: '栗宝宝', img: 'SM_Goomba.jpg', game: '', series: '马力欧' },
    { name: '慢慢龟', img: 'SM_Koopa Troopa.jpg', game: '', series: '马力欧' },
    { name: '害羞幽灵', img: 'SM_Boo.jpg', game: '', series: '马力欧' },
    { name: '瓦力欧', img: 'SM_Wario.jpg', game: '', series: '马力欧' },
    { name: '瓦路易吉', img: 'SM_Waluigi.jpg', game: '', series: '马力欧' },
    { name: '耀西', img: 'SM_Yoshi.png', game: '', series: '马力欧' },
    { name: '马力欧', img: 'SMO_Mario - Wedding.jpg', game: '', series: '马力欧' },
    { name: '碧姬公主', img: 'SMO_Peach - Wedding.png', game: '', series: '马力欧' },
    { name: '酷霸王', img: 'SMO_Bowser.jpg', game: '', series: '马力欧' },
    { name: '', img: 'SN_Shovel Knight.png', game: '', series: '铲子骑士' },
    { name: '', img: 'SN_Shovel Knight (Gold Edition).png', game: '', series: '铲子骑士' },
    { name: '', img: 'SN_Shovel Knight NEW.png', game: '', series: '铲子骑士' },
    { name: '', img: 'SN_Shovel Knight Unlocked.png', game: '', series: '铲子骑士' },
    { name: '', img: 'SN_Plague Knight.png', game: '', series: '铲子骑士' },
    { name: '', img: 'SN_King Knight.png', game: '', series: '铲子骑士' },
    { name: '', img: 'SN_Specter Knight.png', game: '', series: '铲子骑士' },
    { name: '', img: 'Splatoon_麻辣鱿物小拟.jpg', game: '', series: '喷射战士' },
    { name: '', img: 'Splatoon_麻辣鱿物小萤.jpg', game: '', series: '喷射战士' },
    { name: '', img: 'Splatoon_鱿鱼族男孩(紫色).jpg', game: '', series: '喷射战士' },
    { name: '', img: 'Splatoon_鱿鱼族男孩.jpg', game: '', series: '喷射战士' },
    { name: '', img: 'Splatoon_鱿鱼族女孩(青柠绿).jpg', game: '', series: '喷射战士' },
    { name: '', img: 'Splatoon_鱿鱼族女孩.jpg', game: '', series: '喷射战士' },
    { name: '', img: 'Splatoon_鱿鱼族乌贼(橙色).jpg', game: '', series: '喷射战士' },
    { name: '', img: 'Splatoon_鱿鱼族乌贼.jpg', game: '', series: '喷射战士' },
    { name: '', img: 'Splatoon2_腕儿姐妹饭田.jpg', game: '', series: '喷射战士' },
    { name: '', img: 'Splatoon2_腕儿姐妹小姬.jpg', game: '', series: '喷射战士' },
    { name: '', img: 'Splatoon2_鱿鱼族男孩.jpg', game: '', series: '喷射战士' },
    { name: '', img: 'Splatoon2_鱿鱼族女孩.jpg', game: '', series: '喷射战士' },
    { name: '', img: 'Splatoon2_鱿鱼族乌贼.jpg', game: '', series: '喷射战士' },
    { name: '', img: 'Splatoon2_章鱼圈男孩.jpg', game: '', series: '喷射战士' },
    { name: '', img: 'Splatoon2_章鱼圈女孩.jpg', game: '', series: '喷射战士' },
    { name: '', img: 'Splatoon2_章鱼圈章鱼.jpg', game: '', series: '喷射战士' },
    { name: '', img: 'Splatoon3_麻辣鱿物小拟(幻界).jpg', game: '', series: '喷射战士' },
    { name: '', img: 'Splatoon3_麻辣鱿物小萤(幻界).jpg', game: '', series: '喷射战士' },
    { name: '', img: 'Splatoon3_腕儿姐妹饭田(秩序篇).jpg', game: '', series: '喷射战士' },
    { name: '', img: 'Splatoon3_腕儿姐妹小姬(秩序篇).jpg', game: '', series: '喷射战士' },
    { name: '', img: 'Splatoon3_小鲑鱼.jpg', game: '', series: '喷射战士' },
    { name: '', img: 'Splatoon3_鱿鱼族.jpg', game: '', series: '喷射战士' },
    { name: '', img: 'Splatoon3_鱼浆帮鬼福.jpg', game: '', series: '喷射战士' },
    { name: '', img: 'Splatoon3_鱼浆帮曼曼.jpg', game: '', series: '喷射战士' },
    { name: '', img: 'Splatoon3_鱼浆帮莎莎.jpg', game: '', series: '喷射战士' },
    { name: '', img: 'Splatoon3_章鱼圈.jpg', game: '', series: '喷射战士' },
    { name: '', img: 'SSB_AC_Isabelle.jpg', game: '任天堂大乱斗', series: '动物森友会' },
    { name: '', img: 'SSB_AC_Villager.jpg', game: '任天堂大乱斗', series: '动物森友会' },
    { name: '', img: 'SSB_BJ_Bayonetta.jpg', game: '任天堂大乱斗', series: '贝优妮塔' },
    { name: '', img: 'SSB_BJ_Bayonetta P2.jpg', game: '任天堂大乱斗', series: '贝优妮塔' },
    { name: '', img: 'SSB_BK_Banjo & Kazooie.jpg', game: '任天堂大乱斗', series: '' },
    { name: '', img: 'SSB_Castle_Simon.jpg', game: '任天堂大乱斗', series: '恶魔城' },
    { name: '', img: 'SSB_Castle_Richter.jpg', game: '任天堂大乱斗', series: '恶魔城' },
    { name: '咚奇刚', img: 'SSB_DK_Donkey Kong.jpg', game: '任天堂大乱斗', series: '咚奇刚' },
    { name: '迪迪', img: 'SSB_DK_Diddy Kong.jpg', game: '任天堂大乱斗', series: '咚奇刚' },
    { name: '', img: 'SSB_DK_King K. Rool.png', game: '任天堂大乱斗', series: '咚奇刚' },
    { name: '', img: 'SSB_Duck Hunt Duo.jpg', game: '任天堂大乱斗', series: '' },
    { name: '', img: 'SSB_DM_Dr Mario.jpg', game: '任天堂大乱斗', series: '马力欧' },
    { name: '勇者', img: 'SSB_DQ_Hero.jpg', game: '任天堂大乱斗', series: '勇者斗恶龙' },
    { name: '库洛姆', img: 'SSB_FE_Chrom.jpg', game: '任天堂大乱斗', series: '火焰纹章' },
    { name: '卡姆依', img: 'SSB_FE_Corrin P1.jpg', game: '任天堂大乱斗', series: '火焰纹章' },
    { name: '卡姆依', img: 'SSB_FE_Corrin P2.jpg', game: '任天堂大乱斗', series: '火焰纹章' },
    { name: '艾克', img: 'SSB_FE_Ike.jpg', game: '任天堂大乱斗', series: '火焰纹章' },
    { name: '露琪亚', img: 'SSB_FE_Lucina.jpg', game: '任天堂大乱斗', series: '火焰纹章' },
    { name: '马尔斯', img: 'SSB_FE_Marth.jpg', game: '任天堂大乱斗', series: '火焰纹章' },
    { name: '帕鲁迪娜', img: 'SSB_FE_Palutena.jpg', game: '任天堂大乱斗', series: '火焰纹章' },
    { name: '鲁弗莱', img: 'SSB_FE_Robin.jpg', game: '任天堂大乱斗', series: '火焰纹章' },
    { name: '罗伊', img: 'SSB_FE_Roy.jpg', game: '任天堂大乱斗', series: '火焰纹章' },
    { name: '贝雷特', img: 'SSB_FE_Byleth.jpg', game: '任天堂大乱斗', series: '火焰纹章' },
    { name: '克劳德', img: 'SSB_FF_Cloud.jpg', game: '任天堂大乱斗', series: '最终幻想' },
    { name: '克劳德', img: 'SSB_FF_Cloud P2.jpg', game: '任天堂大乱斗', series: '最终幻想' },
    { name: '萨菲罗斯', img: 'SSB_FF_Sephiroth.jpg', game: '任天堂大乱斗', series: '最终幻想' },
    { name: '', img: 'SSB_FZ_Captain Falcon.jpg', game: '任天堂大乱斗', series: '' },
    { name: '', img: 'SSB_Ice Climbers.png', game: '任天堂大乱斗', series: '' },
    { name: '', img: 'SSB_KH_Sora.jpg', game: '任天堂大乱斗', series: '王国之心' },
    { name: '', img: 'SSB_KI_Pit.jpg', game: '任天堂大乱斗', series: '光之神话' },
    { name: '', img: 'SSB_KI_Dark Pit.jpg', game: '任天堂大乱斗', series: '光之神话' },
    { name: '', img: 'SSB_Kirby_Kirby.jpg', game: '任天堂大乱斗', series: '卡比' },
    { name: '', img: 'SSB_Kirby_Meta Knight.jpg', game: '任天堂大乱斗', series: '卡比' },
    { name: '', img: 'SSB_Kirby_King Dedede.jpg', game: '任天堂大乱斗', series: '卡比' },
    { name: '', img: 'SSB_MC_Steve.png', game: '任天堂大乱斗', series: '我的世界' },
    { name: '', img: 'SSB_MC_Alex.png', game: '任天堂大乱斗', series: '我的世界' },
    { name: '', img: 'SSB_MD_黑暗萨姆斯.jpg', game: '任天堂大乱斗', series: '密特罗德' },
    { name: '', img: 'SSB_MD_利德雷.jpg', game: '任天堂大乱斗', series: '密特罗德' },
    { name: '', img: 'SSB_MD_零装甲萨姆斯.jpg', game: '任天堂大乱斗', series: '密特罗德' },
    { name: '', img: 'SSB_MD_萨姆斯.jpg', game: '任天堂大乱斗', series: '密特罗德' },
    { name: '', img: 'SSB_MG_Snake.png', game: '任天堂大乱斗', series: '合金装备' },
    { name: '', img: 'SSB_Mii Swordsman.jpg', game: '任天堂大乱斗', series: '' },
    { name: '', img: 'SSB_Mii Fighter.jpg', game: '任天堂大乱斗', series: '' },
    { name: '', img: 'SSB_Mii Gunner.jpg', game: '任天堂大乱斗', series: '' },
    { name: '', img: 'SSB_Min Min.jpg', game: '任天堂大乱斗', series: '' },
    { name: '', img: 'SSB_MM_Mega Man.jpg', game: '任天堂大乱斗', series: '洛克人' },
    { name: '', img: 'SSB_MM_Mega Man (Gold Edition).jpg', game: '任天堂大乱斗', series: '洛克人' },
    { name: '', img: 'SSB_Mother_Ness.jpg', game: '任天堂大乱斗', series: 'Mother' },
    { name: '', img: 'SSB_Mother_Lucas.jpg', game: '任天堂大乱斗', series: 'Mother' },
    { name: '', img: 'SSB_Mr GAME & WATCH.jpg', game: '任天堂大乱斗', series: '' },
    { name: '', img: 'SSB_MT_Little Mac.jpg', game: '任天堂大乱斗', series: '' },
    { name: '', img: 'SSB_P5_Joker.jpg', game: '任天堂大乱斗', series: 'Persona 5' },
    { name: '', img: 'SSB_Pac Man.jpg', game: '任天堂大乱斗', series: '吃豆人' },
    { name: '', img: 'SSB_Pikmin_Oilmar.jpg', game: '任天堂大乱斗', series: '皮克敏' },
    { name: '训练家', img: 'SSB_PM_Pokémon Trainer.jpg', game: '任天堂大乱斗', series: '宝可梦' },
    { name: '杰尼龟', img: 'SSB_PM_Squirtle.png', game: '任天堂大乱斗', series: '宝可梦' },
    { name: '妙蛙花', img: 'SSB_PM_Ivysaur.png', game: '任天堂大乱斗', series: '宝可梦' },
    { name: '喷火龙', img: 'SSB_PM_Charizard.jpg', game: '任天堂大乱斗', series: '宝可梦' },
    { name: '皮丘', img: 'SSB_PM_Pichu.jpg', game: '任天堂大乱斗', series: '宝可梦' },
    { name: '皮卡超', img: 'SSB_PM_Pikachu.jpg', game: '任天堂大乱斗', series: '宝可梦' },
    { name: '甲贺忍蛙', img: 'SSB_PM_Greninja.jpg', game: '任天堂大乱斗', series: '宝可梦' },
    { name: '炽焰咆啸虎', img: 'SSB_PM_Incineroar.jpg', game: '任天堂大乱斗', series: '宝可梦' },
    { name: '胖丁', img: 'SSB_PM_Jigglypuff.jpg', game: '任天堂大乱斗', series: '宝可梦' },
    { name: '卢卡利欧', img: 'SSB_PM_Lucario.jpg', game: '任天堂大乱斗', series: '宝可梦' },
    { name: '超梦', img: 'SSB_PM_Mewtwo.jpg', game: '任天堂大乱斗', series: '宝可梦' },
    { name: '', img: 'SSB_ROB NES.jpg', game: '任天堂大乱斗', series: '' },
    { name: '', img: 'SSB_ROB Famicom Edition.jpg', game: '任天堂大乱斗', series: '' },
    { name: '', img: 'SSB_SF_Fox.jpg', game: '任天堂大乱斗', series: '星际火狐' },
    { name: '', img: 'SSB_SF_Falco.jpg', game: '任天堂大乱斗', series: '星际火狐' },
    { name: '', img: 'SSB_SF_Wolf.png', game: '任天堂大乱斗', series: '星际火狐' },
    { name: '', img: 'SSB_SF_Terry.jpg', game: '任天堂大乱斗', series: '街头霸王' },
    { name: '', img: 'SSB_SF_Kazuya.jpg', game: '任天堂大乱斗', series: '街头霸王' },
    { name: '', img: 'SSB_SF_Ken.png', game: '任天堂大乱斗', series: '街头霸王' },
    { name: '', img: 'SSB_SF_Ryu.jpg', game: '任天堂大乱斗', series: '街头霸王' },
    { name: '马力欧', img: 'SSB_SM_Mario.jpg', game: '任天堂大乱斗', series: '马力欧' },
    { name: '路易吉', img: 'SSB_SM_Luigi.jpg', game: '任天堂大乱斗', series: '马力欧' },
    { name: '碧姬公主', img: 'SSB_SM_Peach.jpg', game: '任天堂大乱斗', series: '马力欧' },
    { name: '罗洁塔', img: 'SSB_SM_Rosalina.jpg', game: '任天堂大乱斗', series: '马力欧' },
    { name: '黛西公主', img: 'SSB_SM_Daisy.png', game: '任天堂大乱斗', series: '马力欧' },
    { name: '耀西', img: 'SSB_SM_Yoshi.jpg', game: '任天堂大乱斗', series: '马力欧' },
    { name: '酷霸王', img: 'SSB_SM_Bowser.jpg', game: '任天堂大乱斗', series: '马力欧' },
    { name: '小酷霸', img: 'SSB_SM_Bowser Jr..jpg', game: '任天堂大乱斗', series: '马力欧' },
    { name: '吞食花', img: 'SSB_SM_Piranha Plant.png', game: '任天堂大乱斗', series: '马力欧' },
    { name: '瓦力欧', img: 'SSB_SM_Wario.jpg', game: '任天堂大乱斗', series: '马力欧' },
    { name: '', img: 'SSB_Sonic.jpg', game: '任天堂大乱斗', series: '索尼克' },
    { name: '', img: 'SSB_Splatoon_Inkling Girl.png', game: '任天堂大乱斗', series: '喷射战士' },
    { name: '', img: 'SSB_Wii Fit Trainer.jpg', game: '任天堂大乱斗', series: '' },
    { name: '修尔克', img: 'SSB_XC_Shulk.jpg', game: '任天堂大乱斗', series: '异度神剑' },
    { name: '光', img: 'SSB_XC_Mythra.jpg', game: '任天堂大乱斗', series: '异度神剑' },
    { name: '焰', img: 'SSB_XC_Pyra.jpg', game: '任天堂大乱斗', series: '异度神剑' },
    { name: '林克', img: 'SSB_Zelda_Link.jpg', game: '任天堂大乱斗', series: '塞尔达' },
    { name: '林克', img: 'SSB_Zelda_Toon Link.jpg', game: '任天堂大乱斗', series: '塞尔达' },
    { name: '林克', img: 'SSB_Zelda_Young Link.png', game: '任天堂大乱斗', series: '塞尔达' },
    { name: '塞尔达', img: 'SSB_Zelda_Zelda.jpg', game: '任天堂大乱斗', series: '塞尔达' },
    { name: '希克', img: 'SSB_Zelda_Sheik.jpg', game: '任天堂大乱斗', series: '塞尔达' },
    { name: '加侬多夫', img: 'SSB_Zelda_Ganondorf.jpg', game: '任天堂大乱斗', series: '塞尔达' },
    { name: '诺亚', img: 'XC3_诺亚.jpg', game: '异度神剑3', series: '异度神剑' },
    { name: '弥央', img: 'XC3_弥央.jpg', game: '异度神剑3', series: '异度神剑' },
    { name: '', img: 'Yoshi_Blue Yoshi.png', game: '毛线耀西', series: '耀西' },
    { name: '', img: 'Yoshi_Green Yoshi.png', game: '毛线耀西', series: '耀西' },
    { name: '', img: 'Yoshi_Pink Yoshi.png', game: '毛线耀西', series: '耀西' },
    { name: '', img: 'Yoshi_Mega Yoshi.png', game: '毛线耀西', series: '耀西' },
    { name: '', img: 'Yoshi_毛线波奇.jpg', game: '毛线耀西', series: '耀西' },
    { name: '林克', img: 'Zelda_初始林克.jpg', game: '塞尔达 30周年', series: '塞尔达' },
    { name: '林克', img: 'Zelda_风之杖卡通林克.jpg', game: '塞尔达 30周年', series: '塞尔达' },
    { name: '塞尔达', img: 'Zelda_风之杖塞尔达.jpg', game: '塞尔达 30周年', series: '塞尔达' },
    { name: '林克', img: 'Zelda_时之笛林克.jpg', game: '塞尔达 30周年', series: '塞尔达' },
    { name: '林克', img: 'Zelda_魔吉拉的面具林克.jpg', game: '塞尔达 魔吉拉的面具', series: '塞尔达' },
    { name: '林克', img: 'Zelda_黄昏公主林克.jpg', game: '塞尔达 黄昏公主', series: '塞尔达' },
    { name: '林克', img: 'Zelda_黄昏公主野狼林克.jpg', game: '塞尔达 黄昏公主', series: '塞尔达' },
    { name: '林克', img: 'Zelda_御天之剑林克.jpg', game: '塞尔达 御天之剑', series: '塞尔达' },
    { name: '塞尔达', img: 'Zelda_御天之剑塞尔达与洛夫特飞鸟.jpg', game: '塞尔达 御天之剑', series: '塞尔达' },
    { name: '林克', img: 'Zelda_旷野之息骑士林克.jpg', game: '塞尔达 旷野之息', series: '塞尔达' },
    { name: '林克', img: 'Zelda_旷野之息射手林克.jpg', game: '塞尔达 旷野之息', series: '塞尔达' },
    { name: '塞尔达', img: 'Zelda_旷野之息塞尔达.jpg', game: '塞尔达 旷野之息', series: '塞尔达' },
    { name: '力巴尔', img: 'Zelda_旷野之息力巴尔.jpg', game: '塞尔达 旷野之息', series: '塞尔达' },
    { name: '米法', img: 'Zelda_旷野之息米法.jpg', game: '塞尔达 旷野之息', series: '塞尔达' },
    { name: '乌尔波扎', img: 'Zelda_旷野之息乌尔波扎.jpg', game: '塞尔达 旷野之息', series: '塞尔达' },
    { name: '达尔克尔', img: 'Zelda_旷野之息达尔克尔.jpg', game: '塞尔达 旷野之息', series: '塞尔达' },
    { name: '守护者', img: 'Zelda_旷野之息守护者.jpg', game: '塞尔达 旷野之息', series: '塞尔达' },
    { name: '波克布林', img: 'Zelda_旷野之息波克布林.jpg', game: '塞尔达 旷野之息', series: '塞尔达' },
    { name: '林克', img: 'Zelda_织梦岛林克.jpg', game: '塞尔达 织梦岛', series: '塞尔达' },
    { name: '林克', img: 'Zelda_王国之泪林克.jpg', game: '塞尔达 王国之泪', series: '塞尔达' },
    { name: '塞尔达', img: 'Zelda_王国之泪塞尔达.jpg', game: '塞尔达 王国之泪', series: '塞尔达' },
    { name: '加侬多夫', img: 'Zelda_王国之泪加侬多夫.jpg', game: '塞尔达 王国之泪', series: '塞尔达' },
    { name: '丘栗', img: 'Zelda_王国之泪丘栗.jpg', game: '塞尔达 王国之泪', series: '塞尔达' },
    { name: '希多', img: 'Zelda_王国之泪希多.jpg', game: '塞尔达 王国之泪', series: '塞尔达' },
    { name: '露珠', img: 'Zelda_王国之泪露珠.jpg', game: '塞尔达 王国之泪', series: '塞尔达' },
    { name: '阿沅', img: 'Zelda_王国之泪阿沅.jpg', game: '塞尔达 王国之泪', series: '塞尔达' },
]

export const games = [
    { name: '' },
]